// Code generated by internal/gen. DO NOT EDIT.

package p374

import "math/bits"

// Field constants for p = 117·2^374 − 1, a 381-bit prime. Elements
// use 6 limbs, and R = 2^(64·6) is the Montgomery constant.
const (
	fpLimbs = 6
	fpSize  = 48 // the length of an encoded element in bytes

	fpPTop = 0x1d40000000000000 // the top limb of p + 1; the other limbs are zero
)

var (
	fpP       = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x1d3fffffffffffff}
	fpR       = [fpLimbs]uint64{0x0000000000000008, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x1600000000000000}
	fpR2      = [fpLimbs]uint64{0x8c08c08c08c08c55, 0x08c08c08c08c08c0, 0xc08c08c08c08c08c, 0x8c08c08c08c08c08, 0x08c08c08c08c08c0, 0x0a4c08c08c08c08c}
	fpExpInv  = [fpLimbs]uint64{0xfffffffffffffffd, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x1d3fffffffffffff} // p − 2
	fpExpSqrt = [fpLimbs]uint64{0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0750000000000000} // (p + 1)/4
	fpExpLeg  = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0e9fffffffffffff} // (p − 1)/2

	// fpExpRsqrt is (p − 3)/4: x^((p − 3)/4) is 1/√x for a square x.
	fpExpRsqrt = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x074fffffffffffff}

	fpThird = [fpLimbs]uint64{0x5555555555555558, 0x5555555555555555, 0x5555555555555555, 0x5555555555555555, 0x5555555555555555, 0x0755555555555555} // 1/3 in Montgomery form

	// fpNonSquareSteps holds, in increasing order, the first integers h ≥ 1
	// for which 1 + h² is not a square in GF(p).
	fpNonSquareSteps = [...]uint16{
		2, 3, 4, 6, 8, 9, 11, 14, 15, 20, 21, 24, 25, 26, 28, 31,
		32, 34, 35, 37, 38, 39, 43, 48, 51, 52, 54, 57, 58, 60, 61, 63,
		66, 70, 72, 74, 79, 86, 87, 88, 89, 91, 92, 93, 94, 96, 98, 99,
		100, 102, 103, 104, 105, 106, 108, 109, 110, 111, 116, 117, 118, 122, 123, 128,
		129, 131, 133, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 147, 150,
		151, 152, 155, 158, 159, 160, 164, 169, 170, 171, 172, 173, 174, 176, 179, 181,
		182, 183, 184, 185, 187, 188, 191, 193, 194, 196, 197, 198, 200, 205, 208, 210,
		213, 217, 218, 219, 224, 227, 228, 229, 233, 234, 238, 240, 241, 242, 244, 247,
	}
)

// add sets z = x + y and returns z.
func (z *fp) add(x, y *fp) *fp {
	var c, b uint64
	t0, c := bits.Add64(x.l[0], y.l[0], 0)
	t1, c := bits.Add64(x.l[1], y.l[1], c)
	t2, c := bits.Add64(x.l[2], y.l[2], c)
	t3, c := bits.Add64(x.l[3], y.l[3], c)
	t4, c := bits.Add64(x.l[4], y.l[4], c)
	t5, c := bits.Add64(x.l[5], y.l[5], c)
	t0, b = bits.Sub64(t0, 0xffffffffffffffff, 0)
	t1, b = bits.Sub64(t1, 0xffffffffffffffff, b)
	t2, b = bits.Sub64(t2, 0xffffffffffffffff, b)
	t3, b = bits.Sub64(t3, 0xffffffffffffffff, b)
	t4, b = bits.Sub64(t4, 0xffffffffffffffff, b)
	t5, b = bits.Sub64(t5, fpPTop-1, b)
	mask := -b
	z.l[0], c = bits.Add64(t0, mask, 0)
	z.l[1], c = bits.Add64(t1, mask, c)
	z.l[2], c = bits.Add64(t2, mask, c)
	z.l[3], c = bits.Add64(t3, mask, c)
	z.l[4], c = bits.Add64(t4, mask, c)
	z.l[5], c = bits.Add64(t5, (fpPTop-1)&mask, c)
	return z
}

// sub sets z = x − y and returns z.
func (z *fp) sub(x, y *fp) *fp {
	var b, c uint64
	t0, b := bits.Sub64(x.l[0], y.l[0], 0)
	t1, b := bits.Sub64(x.l[1], y.l[1], b)
	t2, b := bits.Sub64(x.l[2], y.l[2], b)
	t3, b := bits.Sub64(x.l[3], y.l[3], b)
	t4, b := bits.Sub64(x.l[4], y.l[4], b)
	t5, b := bits.Sub64(x.l[5], y.l[5], b)
	mask := -b
	z.l[0], c = bits.Add64(t0, mask, 0)
	z.l[1], c = bits.Add64(t1, mask, c)
	z.l[2], c = bits.Add64(t2, mask, c)
	z.l[3], c = bits.Add64(t3, mask, c)
	z.l[4], c = bits.Add64(t4, mask, c)
	z.l[5], c = bits.Add64(t5, (fpPTop-1)&mask, c)
	return z
}

// fpMulGeneric sets z = x·y/R mod p. The inputs must be below p, and z may
// alias them.
func fpMulGeneric(z, x, y *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6 uint64
	var h0, h1, h2, h3, h4, h5 uint64
	var l0, l1, l2, l3, l4, l5 uint64
	var r0, r1, r2, r3, r4, r5, r6 uint64
	// Row 0: t += x·y[0].
	h0, l0 = bits.Mul64(x[0], y[0])
	h1, l1 = bits.Mul64(x[1], y[0])
	h2, l2 = bits.Mul64(x[2], y[0])
	h3, l3 = bits.Mul64(x[3], y[0])
	h4, l4 = bits.Mul64(x[4], y[0])
	h5, l5 = bits.Mul64(x[5], y[0])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	// Row 1: t += x·y[1].
	h0, l0 = bits.Mul64(x[0], y[1])
	h1, l1 = bits.Mul64(x[1], y[1])
	h2, l2 = bits.Mul64(x[2], y[1])
	h3, l3 = bits.Mul64(x[3], y[1])
	h4, l4 = bits.Mul64(x[4], y[1])
	h5, l5 = bits.Mul64(x[5], y[1])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	// Row 2: t += x·y[2].
	h0, l0 = bits.Mul64(x[0], y[2])
	h1, l1 = bits.Mul64(x[1], y[2])
	h2, l2 = bits.Mul64(x[2], y[2])
	h3, l3 = bits.Mul64(x[3], y[2])
	h4, l4 = bits.Mul64(x[4], y[2])
	h5, l5 = bits.Mul64(x[5], y[2])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	// Row 3: t += x·y[3].
	h0, l0 = bits.Mul64(x[0], y[3])
	h1, l1 = bits.Mul64(x[1], y[3])
	h2, l2 = bits.Mul64(x[2], y[3])
	h3, l3 = bits.Mul64(x[3], y[3])
	h4, l4 = bits.Mul64(x[4], y[3])
	h5, l5 = bits.Mul64(x[5], y[3])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	// Row 4: t += x·y[4].
	h0, l0 = bits.Mul64(x[0], y[4])
	h1, l1 = bits.Mul64(x[1], y[4])
	h2, l2 = bits.Mul64(x[2], y[4])
	h3, l3 = bits.Mul64(x[3], y[4])
	h4, l4 = bits.Mul64(x[4], y[4])
	h5, l5 = bits.Mul64(x[5], y[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	// Row 5: t += x·y[5].
	h0, l0 = bits.Mul64(x[0], y[5])
	h1, l1 = bits.Mul64(x[1], y[5])
	h2, l2 = bits.Mul64(x[2], y[5])
	h3, l3 = bits.Mul64(x[3], y[5])
	h4, l4 = bits.Mul64(x[4], y[5])
	h5, l5 = bits.Mul64(x[5], y[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = 0
	t4, c = bits.Add64(t4, l0, 0)
	t5, _ = bits.Add64(t5, h0, c)
	var b uint64
	t0, b = bits.Sub64(t0, 0xffffffffffffffff, 0)
	t1, b = bits.Sub64(t1, 0xffffffffffffffff, b)
	t2, b = bits.Sub64(t2, 0xffffffffffffffff, b)
	t3, b = bits.Sub64(t3, 0xffffffffffffffff, b)
	t4, b = bits.Sub64(t4, 0xffffffffffffffff, b)
	t5, b = bits.Sub64(t5, fpPTop-1, b)
	mask := -b
	z[0], c = bits.Add64(t0, mask, 0)
	z[1], c = bits.Add64(t1, mask, c)
	z[2], c = bits.Add64(t2, mask, c)
	z[3], c = bits.Add64(t3, mask, c)
	z[4], c = bits.Add64(t4, mask, c)
	z[5], c = bits.Add64(t5, (fpPTop-1)&mask, c)
}

// fpSquareGeneric sets z = x²/R mod p. The input must be below p, and z may
// alias it.
func fpSquareGeneric(z, x *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11 uint64
	var h0, h1, h2, h3, h4, h5 uint64
	var l0, l1, l2, l3, l4, l5 uint64
	var r0, r1, r2, r3, r4, r5 uint64
	// Cross products with x[0].
	h0, l0 = bits.Mul64(x[0], x[1])
	h1, l1 = bits.Mul64(x[0], x[2])
	h2, l2 = bits.Mul64(x[0], x[3])
	h3, l3 = bits.Mul64(x[0], x[4])
	h4, l4 = bits.Mul64(x[0], x[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t1, c = bits.Add64(t1, r0, 0)
	t2, c = bits.Add64(t2, r1, c)
	t3, c = bits.Add64(t3, r2, c)
	t4, c = bits.Add64(t4, r3, c)
	t5, c = bits.Add64(t5, r4, c)
	t6, c = bits.Add64(t6, r5, c)
	t7 = c
	// Cross products with x[1].
	h0, l0 = bits.Mul64(x[1], x[2])
	h1, l1 = bits.Mul64(x[1], x[3])
	h2, l2 = bits.Mul64(x[1], x[4])
	h3, l3 = bits.Mul64(x[1], x[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, _ = bits.Add64(h3, 0, c)
	t3, c = bits.Add64(t3, r0, 0)
	t4, c = bits.Add64(t4, r1, c)
	t5, c = bits.Add64(t5, r2, c)
	t6, c = bits.Add64(t6, r3, c)
	t7, c = bits.Add64(t7, r4, c)
	t8 = c
	// Cross products with x[2].
	h0, l0 = bits.Mul64(x[2], x[3])
	h1, l1 = bits.Mul64(x[2], x[4])
	h2, l2 = bits.Mul64(x[2], x[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, _ = bits.Add64(h2, 0, c)
	t5, c = bits.Add64(t5, r0, 0)
	t6, c = bits.Add64(t6, r1, c)
	t7, c = bits.Add64(t7, r2, c)
	t8, c = bits.Add64(t8, r3, c)
	t9 = c
	// Cross products with x[3].
	h0, l0 = bits.Mul64(x[3], x[4])
	h1, l1 = bits.Mul64(x[3], x[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, _ = bits.Add64(h1, 0, c)
	t7, c = bits.Add64(t7, r0, 0)
	t8, c = bits.Add64(t8, r1, c)
	t9, c = bits.Add64(t9, r2, c)
	t10 = c
	// Cross products with x[4].
	h0, l0 = bits.Mul64(x[4], x[5])
	r0 = l0
	r1 = h0
	t9, c = bits.Add64(t9, r0, 0)
	t10, c = bits.Add64(t10, r1, c)
	t11 = c
	// Double the cross products; t0 is zero.
	t11 = t11<<1 | t10>>63
	t10 = t10<<1 | t9>>63
	t9 = t9<<1 | t8>>63
	t8 = t8<<1 | t7>>63
	t7 = t7<<1 | t6>>63
	t6 = t6<<1 | t5>>63
	t5 = t5<<1 | t4>>63
	t4 = t4<<1 | t3>>63
	t3 = t3<<1 | t2>>63
	t2 = t2<<1 | t1>>63
	t1 <<= 1
	// Add the squares of the limbs.
	h0, l0 = bits.Mul64(x[0], x[0])
	h1, l1 = bits.Mul64(x[1], x[1])
	h2, l2 = bits.Mul64(x[2], x[2])
	h3, l3 = bits.Mul64(x[3], x[3])
	h4, l4 = bits.Mul64(x[4], x[4])
	h5, l5 = bits.Mul64(x[5], x[5])
	t0, c = bits.Add64(t0, l0, 0)
	t1, c = bits.Add64(t1, h0, c)
	t2, c = bits.Add64(t2, l1, c)
	t3, c = bits.Add64(t3, h1, c)
	t4, c = bits.Add64(t4, l2, c)
	t5, c = bits.Add64(t5, h2, c)
	t6, c = bits.Add64(t6, l3, c)
	t7, c = bits.Add64(t7, h3, c)
	t8, c = bits.Add64(t8, l4, c)
	t9, c = bits.Add64(t9, h4, c)
	t10, c = bits.Add64(t10, l5, c)
	t11, c = bits.Add64(t11, h5, c)
	// Reduce: add pTop·M at limb N−1 and keep the high N limbs.
	h0, l0 = bits.Mul64(t0, fpPTop)
	m := t5 + l0 // the top limb of M
	h1, l1 = bits.Mul64(t1, fpPTop)
	h2, l2 = bits.Mul64(t2, fpPTop)
	h3, l3 = bits.Mul64(t3, fpPTop)
	h4, l4 = bits.Mul64(t4, fpPTop)
	h5, l5 = bits.Mul64(m, fpPTop)
	var c2, rTop uint64
	r1, c2 = bits.Add64(l1, h0, 0)
	r2, c2 = bits.Add64(l2, h1, c2)
	r3, c2 = bits.Add64(l3, h2, c2)
	r4, c2 = bits.Add64(l4, h3, c2)
	r5, c2 = bits.Add64(l5, h4, c2)
	rTop, _ = bits.Add64(h5, 0, c2)
	_, c = bits.Add64(t5, l0, 0)
	t6, c = bits.Add64(t6, r1, c)
	t7, c = bits.Add64(t7, r2, c)
	t8, c = bits.Add64(t8, r3, c)
	t9, c = bits.Add64(t9, r4, c)
	t10, c = bits.Add64(t10, r5, c)
	t11, _ = bits.Add64(t11, rTop, c)
	var b uint64
	t6, b = bits.Sub64(t6, 0xffffffffffffffff, 0)
	t7, b = bits.Sub64(t7, 0xffffffffffffffff, b)
	t8, b = bits.Sub64(t8, 0xffffffffffffffff, b)
	t9, b = bits.Sub64(t9, 0xffffffffffffffff, b)
	t10, b = bits.Sub64(t10, 0xffffffffffffffff, b)
	t11, b = bits.Sub64(t11, fpPTop-1, b)
	mask := -b
	z[0], c = bits.Add64(t6, mask, 0)
	z[1], c = bits.Add64(t7, mask, c)
	z[2], c = bits.Add64(t8, mask, c)
	z[3], c = bits.Add64(t9, mask, c)
	z[4], c = bits.Add64(t10, mask, c)
	z[5], c = bits.Add64(t11, (fpPTop-1)&mask, c)
}

// fromMontgomery returns the canonical integer value of x as little-endian
// limbs.
func fromMontgomery(x *fp) [fpLimbs]uint64 {
	var c, h, l uint64
	t := x.l
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[5] = 0
	t[4], c = bits.Add64(t[4], l, 0)
	t[5], _ = bits.Add64(t[5], h, c)
	return t
}
