// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p374

import (
	"bytes"
	"crypto/sha3"
	"encoding/binary"
	"math/big"
	"slices"
	"testing"
)

const (
	// randBig returns a small edge case with probability 2/edgeCaseOdds:
	// one of the edgeCaseCount values closest to 0 or to p.
	edgeCaseOdds  = 8
	edgeCaseCount = 3

	// testUint64 is a value that does not fit in an int64.
	testUint64 = 1<<63 + 5
)

// testRand is a deterministic source of test inputs, which keeps failures
// reproducible.
type testRand struct {
	seed    string
	counter uint64
}

func newTestRand(seed string) *testRand {
	return &testRand{seed: seed, counter: 0}
}

// bytes returns n pseudorandom bytes.
func (r *testRand) bytes(n int) []byte {
	r.counter++

	return sha3.SumSHAKE128(binary.LittleEndian.AppendUint64([]byte(r.seed), r.counter), n)
}

// below returns a pseudorandom integer in [0, n). The modulo bias does not
// matter for tests.
func (r *testRand) below(n uint64) uint64 {
	return binary.LittleEndian.Uint64(r.bytes(limbBytes)) % n
}

// prime returns p as a big.Int.
func prime() *big.Int {
	one := big.NewInt(1)

	return new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(primeCofactor), primeExponent), one)
}

func reverse(in []byte) []byte {
	out := slices.Clone(in)
	slices.Reverse(out)

	return out
}

func toBig(elem *fp) *big.Int { return new(big.Int).SetBytes(reverse(elem.bytes())) }

func fromBig(t *testing.T, val *big.Int) fp {
	t.Helper()

	var elem fp
	if !elem.setBytes(reverse(val.FillBytes(make([]byte, fpSize)))) {
		t.Fatalf("setBytes(%x) failed", val)
	}

	return elem
}

// randBig returns a random element of GF(p), biased towards edge cases.
func randBig(rnd *testRand) *big.Int {
	switch rnd.below(edgeCaseOdds) {
	case 0:
		return new(big.Int).SetUint64(rnd.below(edgeCaseCount))
	case 1:
		offset := new(big.Int).SetUint64(1 + rnd.below(edgeCaseCount))

		return offset.Sub(prime(), offset)
	default:
		return new(big.Int).Mod(new(big.Int).SetBytes(rnd.bytes(fpSize+limbBytes)), prime())
	}
}

// bit returns 1 for true and 0 for false.
func bit(cond bool) uint64 {
	if cond {
		return 1
	}

	return 0
}

func TestFpArithmetic(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())
	modP := func(val *big.Int) *big.Int { return val.Mod(val, prime()) }
	inverseOfTwo := new(big.Int).Rsh(new(big.Int).Add(prime(), big.NewInt(1)), 1)

	for range 1000 {
		lhs, rhs := randBig(rnd), randBig(rnd)
		elemX, elemY := fromBig(t, lhs), fromBig(t, rhs)
		check := func(op string, got *fp, want *big.Int) {
			t.Helper()

			if res := toBig(got); res.Cmp(want) != 0 {
				t.Fatalf("%s(%x, %x) = %x, want %x", op, lhs, rhs, res, want)
			}
		}

		var res fp

		check("add", res.add(&elemX, &elemY), modP(new(big.Int).Add(lhs, rhs)))
		check("sub", res.sub(&elemX, &elemY), modP(new(big.Int).Sub(lhs, rhs)))
		check("neg", res.neg(&elemX), modP(new(big.Int).Neg(lhs)))
		check("mul", res.mul(&elemX, &elemY), modP(new(big.Int).Mul(lhs, rhs)))
		check("square", res.square(&elemX), modP(new(big.Int).Mul(lhs, lhs)))
		check("half", res.half(&elemX), modP(new(big.Int).Mul(lhs, inverseOfTwo)))

		double := new(big.Int).Add(lhs, lhs)
		check("mul4", res.mul4(&elemX), modP(double.Add(double, double)))

		aliased := elemX
		check("mul (aliased)", aliased.mul(&aliased, &aliased), modP(new(big.Int).Mul(lhs, lhs)))

		inv := new(big.Int)
		if lhs.Sign() != 0 {
			inv.ModInverse(lhs, prime())
		}

		check("invert", res.invert(&elemX), inv)
		check("selectFrom(1)", res.selectFrom(&elemX, &elemY, 1), lhs)
		check("selectFrom(0)", res.selectFrom(&elemX, &elemY, 0), rhs)
	}
}

// TestFpMulMatchesGeneric checks mul and square, which run assembly on
// amd64, against the generated Go code.
func TestFpMulMatchesGeneric(t *testing.T) {
	t.Parallel()

	checkMulMatchesGeneric(t, newTestRand(t.Name()), 10000)
}

// checkMulMatchesGeneric checks the mul and square methods of fp and fp2
// against the Go functions with the Generic suffix, on count pairs of random
// elements of each field, also with aliased arguments.
func checkMulMatchesGeneric(t *testing.T, rnd *testRand, count int) {
	t.Helper()

	checkFpMulMatchesGeneric(t, rnd, count)
	checkFp2MulMatchesGeneric(t, rnd, count)
}

func checkFpMulMatchesGeneric(t *testing.T, rnd *testRand, count int) {
	t.Helper()

	for range count {
		lhs, rhs := randBig(rnd), randBig(rnd)
		elemX, elemY := fromBig(t, lhs), fromBig(t, rhs)

		var got, want fp
		if fpMulGeneric(&want.l, &elemX.l, &elemY.l); *got.mul(&elemX, &elemY) != want {
			t.Fatalf("mul(%x, %x) = %x, want %x", lhs, rhs, got.l, want.l)
		}

		if fpSquareGeneric(&want.l, &elemX.l); *got.square(&elemX) != want {
			t.Fatalf("square(%x) = %x, want %x", lhs, got.l, want.l)
		}

		got = elemX
		if got.mul(&got, &got); got != want {
			t.Fatalf("mul(%x, %x) aliased = %x, want %x", lhs, lhs, got.l, want.l)
		}

		got = elemY
		if fpSquareGeneric(&want.l, &elemY.l); *got.square(&got) != want {
			t.Fatalf("square(%x) aliased = %x, want %x", rhs, got.l, want.l)
		}
	}
}

func checkFp2MulMatchesGeneric(t *testing.T, rnd *testRand, count int) {
	t.Helper()

	for range count {
		elemX, elemY := toFp2(t, randGf2(rnd)), toFp2(t, randGf2(rnd))

		var got, want fp2
		if fp2MulGeneric(&want, &elemX, &elemY); *got.mul(&elemX, &elemY) != want {
			t.Fatalf("fp2 mul(%x, %x) = %x, want %x", elemX, elemY, got, want)
		}

		got = elemX
		if got.mul(&got, &elemY); got != want {
			t.Fatalf("fp2 mul(%x, %x) aliased = %x, want %x", elemX, elemY, got, want)
		}

		if fp2SquareGeneric(&want, &elemX); *got.square(&elemX) != want {
			t.Fatalf("fp2 square(%x) = %x, want %x", elemX, got, want)
		}

		got = elemX
		if got.square(&got); got != want {
			t.Fatalf("fp2 square(%x) aliased = %x, want %x", elemX, got, want)
		}
	}
}

func TestFpIsSquare(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	for range 1000 {
		val := randBig(rnd)
		elem := fromBig(t, val)

		isSquare := big.Jacobi(val, prime()) >= 0
		if got := elem.isSquare(); got != bit(isSquare) {
			t.Fatalf("isSquare(%x) = %d, want %v", val, got, isSquare)
		}
	}
}

func TestFpNonSquareSteps(t *testing.T) {
	t.Parallel()

	if len(fpNonSquareSteps) != maxSamplingAttempts {
		t.Fatalf("len(fpNonSquareSteps) = %d, want %d", len(fpNonSquareSteps), maxSamplingAttempts)
	}

	// The steps h with 1 + h² not a square, in increasing order.
	var want []int64

	for step := int64(1); len(want) < maxSamplingAttempts; step++ {
		if big.Jacobi(big.NewInt(step*step+1), prime()) == -1 {
			want = append(want, step)
		}
	}

	for idx, got := range fpNonSquareSteps {
		if int64(got) != want[idx] {
			t.Fatalf("fpNonSquareSteps[%d] = %d, want %d", idx, got, want[idx])
		}
	}
}

func TestFpPredicates(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	for range 1000 {
		lhs, rhs := randBig(rnd), randBig(rnd)
		elemX, elemY := fromBig(t, lhs), fromBig(t, rhs)

		if got := elemX.equal(&elemY); got != bit(lhs.Cmp(rhs) == 0) {
			t.Fatalf("equal(%x, %x) = %d", lhs, rhs, got)
		}

		if got := elemX.isZero(); got != bit(lhs.Sign() == 0) {
			t.Fatalf("isZero(%x) = %d", lhs, got)
		}

		if got := elemX.isOdd(); got != uint64(lhs.Bit(0)) {
			t.Fatalf("isOdd(%x) = %d", lhs, got)
		}
	}
}

func TestFpConstants(t *testing.T) {
	t.Parallel()

	var elem fp
	if toBig(&elem).Sign() != 0 || toBig(elem.one()).Cmp(big.NewInt(1)) != 0 {
		t.Error("wrong zero or one")
	}

	if toBig(elem.setUint64(testUint64)).Cmp(new(big.Int).SetUint64(testUint64)) != 0 {
		t.Error("wrong setUint64")
	}
}

func TestFpSetBytesRejects(t *testing.T) {
	t.Parallel()

	var elem fp
	for _, enc := range [][]byte{
		nil,
		make([]byte, fpSize-1),
		make([]byte, fpSize+1),
		bytes.Repeat([]byte{0xff}, fpSize),
		reverse(prime().FillBytes(make([]byte, fpSize))),
	} {
		if elem.setBytes(enc) {
			t.Errorf("setBytes(%x) accepted an invalid encoding", enc)
		}
	}
}

// gf2 is a reference element re + i·im of GF(p²).
type gf2 struct{ re, im *big.Int }

func (a gf2) mul(b gf2) gf2 {
	re := new(big.Int).Sub(new(big.Int).Mul(a.re, b.re), new(big.Int).Mul(a.im, b.im))
	im := new(big.Int).Add(new(big.Int).Mul(a.re, b.im), new(big.Int).Mul(a.im, b.re))

	return gf2{re.Mod(re, prime()), im.Mod(im, prime())}
}

func (a gf2) equal(b gf2) bool { return a.re.Cmp(b.re) == 0 && a.im.Cmp(b.im) == 0 }

func randGf2(rnd *testRand) gf2 { return gf2{randBig(rnd), randBig(rnd)} }

func toFp2(t *testing.T, val gf2) fp2 {
	t.Helper()

	return fp2{fromBig(t, val.re), fromBig(t, val.im)}
}

func fromFp2(elem *fp2) gf2 { return gf2{toBig(&elem.re), toBig(&elem.im)} }

func TestFp2Arithmetic(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())
	unit := gf2{big.NewInt(0), big.NewInt(1)}

	for range 500 {
		lhs, rhs := randGf2(rnd), randGf2(rnd)
		elemX, elemY := toFp2(t, lhs), toFp2(t, rhs)

		var res fp2

		if !fromFp2(res.mul(&elemX, &elemY)).equal(lhs.mul(rhs)) {
			t.Fatal("mul mismatch")
		}

		if !fromFp2(res.square(&elemX)).equal(lhs.mul(lhs)) {
			t.Fatal("square mismatch")
		}

		if !fromFp2(res.mulI(&elemX)).equal(lhs.mul(unit)) {
			t.Fatal("mulI mismatch")
		}

		var one fp2

		one.one()

		if elemX.isZero() == 0 && res.invert(&elemX).mul(&res, &elemX).equal(&one) != 1 {
			t.Fatal("x·(1/x) ≠ 1")
		}
	}
}

func TestFp2Sqrt(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	for range 500 {
		val := randGf2(rnd)
		elem := toFp2(t, val)

		// elem is a square in GF(p²) exactly when its norm is a square in
		// GF(p).
		norm := new(big.Int).Add(new(big.Int).Mul(val.re, val.re), new(big.Int).Mul(val.im, val.im))

		isSquare := big.Jacobi(norm.Mod(norm, prime()), prime()) >= 0
		if elem.isSquare() != bit(isSquare) {
			t.Fatal("isSquare disagrees with the norm")
		}

		var root fp2
		if root.sqrt(&elem) != bit(isSquare) {
			t.Fatal("sqrt success disagrees with isSquare")
		}

		checkFp2Root(t, &elem, &root, isSquare)
	}

	// Small elements of GF(p), whose roots may be purely imaginary, and
	// their products with i.
	const smallCount = 8

	for val := range uint64(smallCount) {
		var elem, root fp2

		elem.setUint64(val)

		if root.sqrt(&elem) != 1 {
			t.Fatalf("sqrt(%d) failed", val)
		}

		checkFp2Root(t, &elem, &root, true)

		elem.mulI(&elem)

		if root.sqrt(&elem) != 1 {
			t.Fatalf("sqrt(%d·i) failed", val)
		}

		checkFp2Root(t, &elem, &root, true)
	}
}

// checkFp2Root checks that root is the square root of elem chosen by
// fp2.sqrt, or zero if elem is not a square.
func checkFp2Root(t *testing.T, elem, root *fp2, isSquare bool) {
	t.Helper()

	var check fp2
	if isSquare && check.square(root).equal(elem) != 1 {
		t.Fatal("sqrt(x)² ≠ x")
	}

	if !isSquare && root.isZero() != 1 {
		t.Fatal("failed sqrt did not return zero")
	}
	// The root has an even real part, or an even imaginary part if the
	// real part is zero.
	if root.re.isOdd() == 1 || (root.re.isZero() == 1 && root.im.isOdd() == 1) {
		t.Fatal("sqrt returned the root with the wrong sign")
	}
}

func TestBatchInvert(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	var elems [5]fp2
	for idx := range elems {
		elems[idx] = toFp2(t, randGf2(rnd))
	}

	inv := elems
	batchInvert(inv[:])

	for idx := range elems {
		var want fp2
		if want.invert(&elems[idx]).equal(&inv[idx]) != 1 {
			t.Fatalf("element %d: wrong inverse", idx)
		}
	}
}

func TestProjectiveInvert(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	const minCount = 2 // projectiveInvert needs at least two elements

	for count := minCount; count <= len(theta4{}); count++ {
		elems := make([]fp, count)

		var prod fp

		prod.one()

		for idx := range elems {
			elems[idx] = fromBig(t, randBig(rnd))
			prod.mul(&prod, &elems[idx])
		}

		inv := slices.Clone(elems)
		projectiveInvert(inv)

		for idx := range elems {
			var got fp
			if got.mul(&inv[idx], &elems[idx]).equal(&prod) != 1 {
				t.Fatalf("count = %d, element %d: elems[i]·inv[i] ≠ product", count, idx)
			}
		}
	}
}

func TestLessLE(t *testing.T) {
	t.Parallel()

	for _, test := range []struct {
		lhs, rhs []byte
		want     uint64
	}{
		{[]byte{1, 0}, []byte{2, 0}, 1},
		{[]byte{2, 0}, []byte{1, 0}, 0},
		{[]byte{2, 0}, []byte{2, 0}, 0},
		{[]byte{0xff, 0}, []byte{0, 1}, 1}, // the last byte is the most significant
		{[]byte{0, 1}, []byte{0xff, 0}, 0},
		{[]byte{0, 0xff}, []byte{0xff, 0xfe}, 0},
	} {
		if got := lessLE(test.lhs, test.rhs); got != test.want {
			t.Errorf("lessLE(%x, %x) = %d, want %d", test.lhs, test.rhs, got, test.want)
		}
	}
}

func BenchmarkFp2(b *testing.B) {
	var lhs, rhs fp2

	lhs.re.setUint64(testUint64)
	lhs.im.setUint64(testUint64 - 1)
	rhs.re.setUint64(testUint64 - 2)
	rhs.im.setUint64(testUint64 - 3)
	b.Run("mul", func(b *testing.B) {
		for b.Loop() {
			lhs.mul(&lhs, &rhs)
		}
	})
	b.Run("mulGeneric", func(b *testing.B) {
		for b.Loop() {
			fp2MulGeneric(&lhs, &lhs, &rhs)
		}
	})
	b.Run("square", func(b *testing.B) {
		for b.Loop() {
			lhs.square(&lhs)
		}
	})
	b.Run("squareGeneric", func(b *testing.B) {
		for b.Loop() {
			fp2SquareGeneric(&lhs, &lhs)
		}
	})
}

func BenchmarkFp(b *testing.B) {
	var lhs, rhs fp

	lhs.setUint64(testUint64)
	rhs.setUint64(testUint64 - 1)
	b.Run("mul", func(b *testing.B) {
		for b.Loop() {
			lhs.mul(&lhs, &rhs)
		}
	})
	b.Run("square", func(b *testing.B) {
		for b.Loop() {
			lhs.square(&lhs)
		}
	})
	b.Run("add", func(b *testing.B) {
		for b.Loop() {
			lhs.add(&lhs, &rhs)
		}
	})
	b.Run("invert", func(b *testing.B) {
		for b.Loop() {
			lhs.invert(&lhs)
		}
	})
}
