// Code generated by internal/gen. DO NOT EDIT.

package p374

// The RigorousMIKE-I parameter set.
const (
	// The prime is p = primeCofactor·2^primeExponent − 1 = 117·2^374 − 1.
	primeCofactor = 117
	primeExponent = 374

	// isogenyExponent is e: the secret isogeny has degree 2^e.
	isogenyExponent = 372
)

// The starting curve E0: y² = x³ + A·x² + x, and x(P0), x(Q0), and
// x(P0 − Q0) for a basis (P0, Q0) of E0[2^(e+2)] with [2^(e+1)]Q0 = (0, 0),
// as hex encodings of elements of GF(p²).
const (
	startingCurveA = "a954e6d4a1f68216f0cd3d075dda2f86a3c92d14c251708591a39a7727f555cca75aa8f8b60faeeeb6c7ca07a36ccf16000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXP        = "f0525e91139ad1f8cc1d84048895a81531361d7d55eaf24155b47ebb4dd19d2e3fb46eba46c512c1f6d250bd64605e03fbd90350b8b9823036aa1a9786118172570c34fcd5f984f7471e03e7ffefe48bee98e099fb8b2c915a94ea9680da9b0d"
	basisXQ        = "f4c9b2e0d516d7a23dae52a1e4d88c3bb798192029df6cba49896f9f428bd3f3500f21f5e9da23f539fd27e883acec00fbd90350b8b9823036aa1a9786118172570c34fcd5f984f7471e03e7ffefe48bee98e099fb8b2c915a94ea9680da9b0d"
	basisXPQ       = "728e08b97458d44d0566eb5236b79a2874679b4ebfe42f7ecf1e772d48ae3811c8e1c75718501b5b1868bc5274862502e57ce4e706c433d79a8680aa069dd59ac69b048651992d11d41ad1a270e6b483cd0c7b0ef843146a226fc0b422a2ee11"
)
