// Code generated by internal/gen. DO NOT EDIT.

package p374

// The RigorousMIKE-I parameter set.
const (
	// The prime is p = primeCofactor·2^primeExponent − 1 = 117·2^374 − 1.
	primeCofactor = 117
	primeExponent = 374

	// isogenyExponent is e: the secret isogeny has degree 2^e.
	isogenyExponent = 372
)

// The starting curve E0: y² = x³ + A·x² + x, and x(P0), x(Q0), and
// x(P0 − Q0) for a basis (P0, Q0) of E0[2^(e+2)] with [2^(e+1)]Q0 = (0, 0),
// as hex encodings of elements of GF(p²).
const (
	startingCurveA = "a954e6d4a1f68216f0cd3d075dda2f86a3c92d14c251708591a39a7727f555cca75aa8f8b60faeeeb6c7ca07a36ccf16000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXP        = "f0525e91139ad1f8cc1d84048895a81531361d7d55eaf24155b47ebb4dd19d2e3fb46eba46c512c1f6d250bd64605e03fbd90350b8b9823036aa1a9786118172570c34fcd5f984f7471e03e7ffefe48bee98e099fb8b2c915a94ea9680da9b0d"
	basisXQ        = "f4c9b2e0d516d7a23dae52a1e4d88c3bb798192029df6cba49896f9f428bd3f3500f21f5e9da23f539fd27e883acec00fbd90350b8b9823036aa1a9786118172570c34fcd5f984f7471e03e7ffefe48bee98e099fb8b2c915a94ea9680da9b0d"
	basisXPQ       = "728e08b97458d44d0566eb5236b79a2874679b4ebfe42f7ecf1e772d48ae3811c8e1c75718501b5b1868bc5274862502e57ce4e706c433d79a8680aa069dd59ac69b048651992d11d41ad1a270e6b483cd0c7b0ef843146a226fc0b422a2ee11"
)

// fourIsogenySplits[l] is the number of multiplications by 4 that the chain
// of key generation applies to a point at level l, one that needs l of them
// to generate a 4-isogeny, before saving it. The entries follow an optimal
// strategy for the costs of multiplying by 4 and of evaluating a 4-isogeny,
// which keeps at most fourIsogenyStackSize points.
var fourIsogenySplits = [...]uint16{
	0, 1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 6, 7, 7,
	8, 8, 8, 8, 9, 9, 9, 9, 10, 11, 12, 12, 12, 13, 14, 15,
	15, 15, 15, 15, 16, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21,
	21, 21, 21, 21, 21, 22, 23, 24, 25, 26, 27, 27, 27, 27, 27, 27,
	28, 28, 29, 30, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	33, 34, 35, 36, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 48, 48, 48, 48, 48,
	48, 49, 49, 49, 49, 49, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59,
	60, 61, 62, 63, 64, 65, 65, 65, 66, 67, 68, 69, 70, 70, 70, 70,
	70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
	70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
}

const fourIsogenyStackSize = 10

// thetaSplits[l] is the number of doublings that the theta chain of the
// shared secret applies to an entry at level l ≥ 2 before saving it. The
// entries follow an optimal strategy for the costs of doubling, of
// evaluating a 2-isogeny, and of the values for doubling on each codomain,
// which keeps at most thetaStackDepth entries for one entry.
var thetaSplits = [...]uint16{
	0, 0, 1, 1, 1, 2, 3, 3, 4, 3, 4, 4, 5, 6, 6, 7,
	6, 7, 7, 8, 7, 8, 9, 10, 10, 10, 11, 10, 11, 11, 12, 13,
	13, 14, 15, 14, 15, 14, 15, 16, 17, 17, 17, 17, 18, 17, 18, 18,
	19, 18, 19, 20, 21, 22, 23, 23, 23, 23, 24, 25, 26, 25, 26, 25,
	26, 25, 26, 27, 28, 28, 28, 28, 28, 29, 28, 29, 30, 31, 31, 31,
	32, 33, 34, 33, 34, 33, 34, 33, 34, 35, 36, 37, 38, 39, 40, 40,
	40, 40, 40, 40, 40, 41, 42, 43, 44, 43, 44, 43, 44, 43, 44, 43,
	44, 45, 46, 46, 46, 46, 46, 46, 47, 46, 47, 48, 47, 48, 49, 50,
	51, 52, 53, 54, 54, 54, 54, 54, 54, 55, 56, 57, 58, 59, 60, 59,
	60, 59, 60, 59, 60, 59, 60, 59, 60, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 69, 70, 71,
	72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 74, 75, 76, 77,
	77, 77, 77, 77, 77, 77, 78, 77, 78, 78, 79, 80, 81, 82, 81, 82,
	81, 82, 81, 82, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 95, 96, 97,
	98, 99, 100, 101, 102, 103, 104, 103, 104, 103, 104, 103, 104, 103, 104, 103,
	104, 103, 104, 103, 104, 103, 104, 103, 104, 103, 104, 105, 106, 107, 108, 109,
	110, 111, 112, 113, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114,
	114, 114, 114, 114, 115, 116, 117, 118, 119, 120, 119, 120, 119, 120, 119, 120,
	119, 120, 119, 120, 119, 120, 121, 122, 123, 122, 123, 124, 125, 126, 127, 128,
	129, 130, 131, 131, 131, 131, 131, 131, 131, 131, 132, 131, 132, 132, 132, 132,
	132, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 141, 142, 141, 142,
	141, 142, 141, 142, 141, 142, 141, 142, 141, 142, 141, 142, 141, 142, 141, 142,
	143, 144,
}

const thetaStackDepth = 12
