// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p374

// This file implements level-2 theta coordinates in dimensions two and four,
// over the base field GF(p). A theta point is a projective tuple, and a theta
// structure is represented by its null point, the image of the identity.

// theta2 is a dimension-2 theta point (x : y : z : t).
type theta2 struct{ x, y, z, t fp }

// hadamard applies the Hadamard transform in place.
func (p *theta2) hadamard() {
	var sumXY, diffXY, sumZT, diffZT fp

	sumXY.add(&p.x, &p.y)
	diffXY.sub(&p.x, &p.y)
	sumZT.add(&p.z, &p.t)
	diffZT.sub(&p.z, &p.t)
	p.x.add(&sumXY, &sumZT)
	p.y.add(&diffXY, &diffZT)
	p.z.sub(&sumXY, &sumZT)
	p.t.sub(&diffXY, &diffZT)
}

// scholtenBasisChange applies the change of basis that follows the Scholten
// isogeny: (x + y + z − t, x − y + z + t, x + y − z + t, x − y − z − t).
func (p *theta2) scholtenBasisChange() {
	var sumXY, diffXY, sumZT, diffZT fp

	sumXY.add(&p.x, &p.y)
	diffXY.sub(&p.x, &p.y)
	sumZT.add(&p.z, &p.t)
	diffZT.sub(&p.z, &p.t)
	p.x.add(&sumXY, &diffZT)
	p.y.add(&diffXY, &sumZT)
	p.z.sub(&sumXY, &diffZT)
	p.t.sub(&diffXY, &sumZT)
}

// square squares each coordinate.
func (p *theta2) square() {
	p.x.square(&p.x)
	p.y.square(&p.y)
	p.z.square(&p.z)
	p.t.square(&p.t)
}

// squareHadamard squares each coordinate, then applies the Hadamard
// transform.
func (p *theta2) squareHadamard() {
	p.square()
	p.hadamard()
}

// mulCoords multiplies p coordinate-wise by q.
func (p *theta2) mulCoords(q *theta2) {
	p.x.mul(&p.x, &q.x)
	p.y.mul(&p.y, &q.y)
	p.z.mul(&p.z, &q.z)
	p.t.mul(&p.t, &q.t)
}

// diffAdd returns P + Q on the dimension-2 theta structure with null point
// null, given P, Q, and P − Q.
func diffAdd(null, ptP, ptQ, ptPQ *theta2) theta2 {
	// Projective ratios of the dual null point: (1/A² : 1/B² : 1/C² : 1/D²)
	// up to scaling, without inversions.
	dual := *null
	dual.squareHadamard()

	var prodAB, prodCD, coefX, coefY, coefZ, coefT fp

	prodAB.mul(&dual.x, &dual.y)
	prodCD.mul(&dual.z, &dual.t)
	coefT.mul(&prodAB, &dual.z)
	coefZ.mul(&prodAB, &dual.t)
	coefY.mul(&prodCD, &dual.x)
	coefX.mul(&prodCD, &dual.y)

	sqP, sqQ := *ptP, *ptQ
	sqP.squareHadamard()
	sqQ.squareHadamard()

	var res theta2

	res.x.mul(&coefX, &sqP.x).mul(&res.x, &sqQ.x)
	res.y.mul(&sqP.y, &sqQ.y).mul(&res.y, &coefY)
	res.z.mul(&sqP.z, &sqQ.z).mul(&res.z, &coefZ)
	res.t.mul(&sqP.t, &sqQ.t).mul(&res.t, &coefT)
	res.hadamard()

	// Divide coordinate-wise by P − Q, scaled to avoid inversions.
	var prodXY, prodZT fp

	prodXY.mul(&ptPQ.x, &ptPQ.y)
	prodZT.mul(&ptPQ.z, &ptPQ.t)
	res.x.mul(&res.x, &prodZT).mul(&res.x, &ptPQ.y)
	res.y.mul(&res.y, &prodZT).mul(&res.y, &ptPQ.x)
	res.z.mul(&res.z, &prodXY).mul(&res.z, &ptPQ.t)
	res.t.mul(&res.t, &prodXY).mul(&res.t, &ptPQ.z)

	return res
}

// twoIsogeny2 computes the (2,2)-isogeny in dimension 2 whose kernel is
// generated by [4]T1 and [4]T2, where T1 and T2 lie above the kernel with
// order 8. It maps each of images in place and returns the codomain null
// point.
//
// If dualIn is set, the inputs are first moved to the dual coordinates; if
// dualOut is set, the outputs are. This allows evaluating a dual isogeny.
func twoIsogeny2(gen1, gen2 *theta2, images []theta2, dualIn, dualOut bool) theta2 {
	ker1, ker2 := *gen1, *gen2
	if dualIn {
		ker1.hadamard()
		ker2.hadamard()
	}

	ker1.squareHadamard()
	ker2.squareHadamard()

	// The names follow the paper: the codomain dual null point is
	// (A : B : C : D), and x, z, t index the kernel coordinates.
	coordXA, coordXB := &ker1.x, &ker1.y
	coordZA, coordTB, coordZC, coordTD := &ker2.x, &ker2.y, &ker2.z, &ker2.t

	var xAtB, zAxB, zCtD fp

	xAtB.mul(coordXA, coordTB)
	zAxB.mul(coordZA, coordXB)
	zCtD.mul(coordZC, coordTD)

	var codomain, inv theta2

	codomain.x.mul(coordZA, &xAtB)
	codomain.y.mul(coordTB, &zAxB)
	codomain.z.mul(coordZC, &xAtB)
	codomain.t.mul(coordTD, &zAxB)

	inv.x.mul(coordXB, &zCtD)
	inv.y.mul(coordXA, &zCtD)
	inv.z = codomain.t
	inv.t = codomain.z

	if dualOut {
		codomain.hadamard()
	}

	for idx := range images {
		img := &images[idx]
		if dualIn {
			img.hadamard()
		}

		img.squareHadamard()
		img.mulCoords(&inv)

		if dualOut {
			img.hadamard()
		}
	}

	return codomain
}

// theta4 is a dimension-4 theta point with 16 coordinates.
type theta4 [16]fp

// hadamard applies the Hadamard transform in place: four layers of
// butterflies (a, b) → (a + b, a − b). On amd64, it runs assembly.
func (p *theta4) hadamard() { theta4Hadamard(p) }

// theta4HadamardGeneric is the Go code of the hadamard method.
func theta4HadamardGeneric(point *theta4) {
	var tmp fp

	for stride := 1; stride < len(point); stride <<= 1 {
		for block := 0; block < len(point); block += stride << 1 {
			for idx := block; idx < block+stride; idx++ {
				tmp = point[idx]
				point[idx].add(&tmp, &point[idx+stride])
				point[idx+stride].sub(&tmp, &point[idx+stride])
			}
		}
	}
}

func (p *theta4) square() {
	for i := range p {
		p[i].square(&p[i])
	}
}

// mulCoords multiplies p coordinate-wise by q.
func (p *theta4) mulCoords(q *theta4) {
	for i := range p {
		p[i].mul(&p[i], &q[i])
	}
}

// gluingBasisChange applies the change of basis used by the final gluing
// isogeny.
func (p *theta4) gluingBasisChange() {
	// Each output block of four is a pair of butterflies on (a ± b, c ± d).
	blocks := [4][4]int{
		{0, 5, 10, 15},
		{4, 1, 14, 11},
		{2, 7, 8, 13},
		{6, 3, 12, 9},
	}

	var res theta4

	for blk, coords := range blocks {
		var sumAB, diffAB, sumCD, diffCD fp

		sumAB.add(&p[coords[0]], &p[coords[1]])
		diffAB.sub(&p[coords[0]], &p[coords[1]])
		sumCD.add(&p[coords[2]], &p[coords[3]])
		diffCD.sub(&p[coords[2]], &p[coords[3]])

		out := res[len(coords)*blk:]
		out[0].add(&sumAB, &sumCD)
		out[1].add(&diffAB, &diffCD)
		out[2].sub(&sumAB, &sumCD)
		out[3].sub(&diffAB, &diffCD)
	}

	*p = res
}

// theta4c is a dimension-4 theta null point in compressed form.
//
// Theta null points of the MIKE theta structures have only ten distinct
// coordinates, because the action of i swaps coordinates in pairs
// (1↔8, 2↔4, 3↔12, 5↔10, 7↔14, 11↔13).
type theta4c [10]fp

// compress returns the compressed form of the null point src.
func compress(src *theta4) theta4c {
	// The coordinates of a null point kept in compressed form.
	kept := [len(theta4c{})]int{0, 1, 2, 3, 5, 6, 7, 9, 11, 15}

	var res theta4c
	for idx, coord := range kept {
		res[idx] = src[coord]
	}

	return res
}

func (c *theta4c) expand() theta4 {
	// The compressed index of each of the 16 coordinates.
	source := [len(theta4{})]int{0, 1, 2, 3, 2, 4, 5, 6, 1, 7, 4, 8, 3, 8, 6, 9}

	var res theta4
	for coord, idx := range source {
		res[coord] = c[idx]
	}

	return res
}

func (c *theta4c) square() {
	for i := range c {
		c[i].square(&c[i])
	}
}

// hadamard applies the Hadamard transform to a compressed null point,
// using its symmetries: 34 additions instead of 64.
func (c *theta4c) hadamard() {
	// All inputs are read before the first output is written. The first
	// layer of butterflies acts on the coordinate pairs below.
	var sum, diff [5]fp

	for idx, pair := range [len(sum)][2]int{{0, 9}, {5, 7}, {2, 8}, {1, 6}, {3, 4}} {
		sum[idx].add(&c[pair[0]], &c[pair[1]])
		diff[idx].sub(&c[pair[0]], &c[pair[1]])
	}

	var mix [6]fp

	mix[0].add(&sum[0], &sum[1])
	mix[1].sub(&sum[0], &sum[1])
	mix[2].add(&diff[0], &diff[1])
	mix[3].sub(&diff[0], &diff[1])
	mix[4].add(&sum[3], &sum[2])
	mix[5].sub(&sum[3], &sum[2])

	var dbl [6]fp

	dbl[0].double(&diff[2])
	dbl[1].double(&diff[3])
	dbl[2].double(&diff[4])
	dbl[3].double(&sum[4])
	dbl[4].double(&mix[4])
	dbl[5].double(&mix[5])

	var outer [2]fp

	outer[0].add(&mix[0], &dbl[3])
	outer[1].sub(&mix[0], &dbl[3])

	c[0].add(&outer[0], &dbl[4])
	c[1].add(&mix[2], &dbl[0])
	c[2].add(&mix[3], &dbl[1])
	c[3].add(&mix[1], &dbl[2])
	c[4].sub(&mix[1], &dbl[2])
	c[5].add(&outer[1], &dbl[5])
	c[6].sub(&mix[2], &dbl[0])
	c[7].sub(&outer[1], &dbl[5])
	c[8].sub(&mix[3], &dbl[1])
	c[9].sub(&outer[0], &dbl[4])
}

// projectiveInvert sets each elems[i] to the product of the other elements,
// which equals 1/elems[i] up to a common factor. It costs 3(n − 1)
// multiplications and no inversion. len(elems) must be between 2 and 16.
func projectiveInvert(elems []fp) {
	last := len(elems) - 1

	var prefix [len(theta4{})]fp // prefix[i] = elems[0]·…·elems[i]

	prefix[0] = elems[0]
	for i := 1; i < last; i++ {
		prefix[i].mul(&prefix[i-1], &elems[i])
	}

	suffix := elems[last] // elems[i+1]·…·elems[last], for the current i

	elems[last] = prefix[last-1]
	for i := last - 1; i > 0; i-- {
		elem := elems[i]
		elems[i].mul(&prefix[i-1], &suffix)
		suffix.mul(&suffix, &elem)
	}

	elems[0] = suffix
}

// theta4Structure is a dimension-4 theta structure, with the values needed
// for doubling.
type theta4Structure struct {
	null      theta4 // the null point
	invNull   theta4 // its coordinate-wise inverse, up to scaling
	invDualSq theta4 // inverse of the squared dual null point, up to scaling
}

// newTheta4Structure returns the structure with the given null point.
func newTheta4Structure(null *theta4) theta4Structure {
	compressed := compress(null)

	return newTheta4StructureCompressed(null, &compressed)
}

// newTheta4StructureFromInvDual returns the structure whose dual null point
// has the given coordinate-wise inverse.
func newTheta4StructureFromInvDual(invDual *theta4) theta4Structure {
	compressed := compress(invDual)
	projectiveInvert(compressed[:])
	compressed.hadamard()
	null := compressed.expand()

	return newTheta4StructureCompressed(&null, &compressed)
}

// newTheta4StructureCompressed computes the precomputed values from the null
// point and its compressed form.
func newTheta4StructureCompressed(null *theta4, compressed *theta4c) theta4Structure {
	inv := *compressed
	projectiveInvert(inv[:])

	dualSq := *compressed
	dualSq.square()
	dualSq.hadamard()
	projectiveInvert(dualSq[:])

	return theta4Structure{
		null:      *null,
		invNull:   inv.expand(),
		invDualSq: dualSq.expand(),
	}
}

// double sets dst = [2]dst.
func (s *theta4Structure) double(dst *theta4) {
	dst.square()
	dst.hadamard()
	dst.square()
	dst.mulCoords(&s.invDualSq)
	dst.hadamard()
	dst.mulCoords(&s.invNull)
}

// doubleN sets dst = [2^n]dst.
func (s *theta4Structure) doubleN(dst *theta4, n int) {
	for range n {
		s.double(dst)
	}
}

// twoIsogeny4 computes the (2,2,2,2)-isogeny whose kernel is determined by
// the points gen1 and gen2 lying above it with order 8, using the symmetries
// of the MIKE theta structures. It maps each of images in place and returns
// the codomain as the coordinate-wise inverse of its dual null point, from
// which newTheta4StructureFromInvDual computes the structure.
func twoIsogeny4(gen1, gen2 *theta4, images []theta4) theta4 {
	kerP, kerQ := *gen1, *gen2
	kerP.square()
	kerP.hadamard()
	kerQ.square()
	kerQ.hadamard()
	invDual := invDualCodomain(&kerP, &kerQ)

	for idx := range images {
		img := &images[idx]
		img.square()
		img.hadamard()
		img.mulCoords(&invDual)
		img.hadamard()
	}

	return invDual
}

// invDualCodomain returns the coordinate-wise inverse of the codomain's dual
// null point, up to scaling, from the squared and transformed kernel points
// kerP and kerQ. It costs 25 multiplications.
func invDualCodomain(kerP, kerQ *theta4) theta4 {
	// Prefix products pre and suffix products suf over the factors below;
	// each coordinate is a product of a prefix and a suffix.
	var pre, suf [8]fp

	pre[0] = kerP[12]
	pre[1].mul(&pre[0], &kerP[5])
	pre[2].mul(&pre[1], &kerQ[1])
	pre[3].mul(&pre[2], &kerP[9])
	pre[4].mul(&pre[3], &kerP[11])
	pre[5].mul(&pre[4], &kerQ[15])
	pre[6].mul(&pre[5], &kerQ[14])
	pre[7].mul(&pre[6], &kerP[6])

	suf[7] = kerP[0]
	suf[6].mul(&suf[7], &kerP[2])
	suf[5].mul(&suf[6], &kerQ[6])
	suf[4].mul(&suf[5], &kerQ[7])
	suf[3].mul(&suf[4], &kerP[15])
	suf[2].mul(&suf[3], &kerP[13])
	suf[1].mul(&suf[2], &kerQ[9])
	suf[0].mul(&suf[1], &kerP[1])

	var res theta4

	res[0].mul(&pre[7], &kerP[4])

	var tmp fp

	tmp.mul(&kerP[8], &kerP[5])
	res[12].mul(&tmp, &suf[1])

	for idx, coord := range [len(pre)]int{5, 1, 9, 11, 15, 14, 6, 4} {
		res[coord].mul(&pre[idx], &suf[idx])
	}

	res[3] = res[12]
	res[10] = res[5]
	res[8] = res[1]
	res[13] = res[11]
	res[7] = res[14]
	res[2] = res[4]

	return res
}

// invariants returns the four absolute MIKE invariants J2, …, J5 of the
// abelian fourfold with this theta structure, normalized so that J1 = 3
// (Algorithm 3 of the MIKE paper).
func (s *theta4Structure) invariants() [4]fp {
	ratios := s.invariantRatios()

	// Jk = Σ (Ii/I0)^k for k = 2, …, 5.
	var sums [4]fp

	for idx := range ratios {
		var pow2, pow3, pow4, pow5 fp

		pow2.square(&ratios[idx])
		pow3.mul(&ratios[idx], &pow2)
		pow4.square(&pow2)
		pow5.mul(&ratios[idx], &pow4)

		if idx == 0 {
			sums = [4]fp{pow2, pow3, pow4, pow5}

			continue
		}

		sums[0].add(&sums[0], &pow2)
		sums[1].add(&sums[1], &pow3)
		sums[2].add(&sums[2], &pow4)
		sums[3].add(&sums[3], &pow5)
	}

	return sums
}

// invariantRatios returns I1/I0, …, I9/I0 for the null point (a0 : … : a15)
// of this theta structure, with the first three doubled.
func (s *theta4Structure) invariantRatios() [9]fp {
	null := &s.null

	// I0, …, I3 are the squares of the Hadamard transform of (a0, a6, a9,
	// a15); I4, …, I9 come from a Hadamard transform of those squares and
	// 16·a3·a5.
	squares := theta2{x: null[0], y: null[6], z: null[9], t: null[15]}
	squares.hadamard()
	squares.square()

	trans := squares
	trans.hadamard()

	var cross fp

	cross.mul(&null[3], &null[5]).mul4(&cross).mul4(&cross)

	var ratios [9]fp

	ratios[0] = squares.y
	ratios[1] = squares.z
	ratios[2] = squares.t
	ratios[3].add(&trans.y, &cross)
	ratios[4].sub(&trans.y, &cross)
	ratios[5].add(&trans.z, &cross)
	ratios[6].sub(&trans.z, &cross)
	ratios[7].add(&trans.t, &cross)
	ratios[8].sub(&trans.t, &cross)

	var inv fp

	inv.invert(&squares.x)

	for idx := range ratios {
		ratios[idx].mul(&ratios[idx], &inv)
	}

	ratios[0].double(&ratios[0])
	ratios[1].double(&ratios[1])
	ratios[2].double(&ratios[2])

	return ratios
}
