// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p758

// This file drives the dimension-4 isogeny chain of the shared secret
// computation, from E × E^σ × E × E^σ to the fourfold whose invariants form
// the shared secret.
//
// The kernel is generated by two points of order 2^(e+2) above it. Each
// 2-isogeny step needs the multiples of order 8 of the kernel generators. A
// strategy saves intermediate multiples on a stack, so that the chain needs
// O(e log e) doublings and evaluations instead of O(e²) doublings. On the
// fourfold, the strategy follows thetaSplits.
//
// Stack entry i holds two kernel generators and a level, levels[i]. A level
// of 1 means the generators are ready for the next step. Each step consumes
// the top entry and lowers the level of the entries below it by one. The
// first step is the three-isogeny gluing, which starts from points on E; the
// remaining e − 3 steps are 2-isogenies between theta structures.
//
// Doubling is far cheaper on E than on the fourfold, so the entries below
// the gluing start on E, with the levels from curveLevels. The gluing
// consumes an entry of level 1 too, but the kernel data provides it.

const (
	// generators is the number of kernel generators in a stack entry.
	generators = 2

	// gluingDepth is the number of 2-isogenies in the gluing beyond the one
	// step it counts as.
	gluingDepth = 2

	// curveSaveLevel is the lowest level of a stack entry on E that is
	// halved into another entry on E.
	curveSaveLevel = 64
)

// isogenyChain returns the codomain of the 2^e-isogeny with the given kernel
// data. The curve point pairs in pairs are the bottom of the stack, with the
// levels curveLevels(e − gluingDepth), and gluing holds the kernel data for
// the gluing steps.
func (c *curve) isogenyChain(gluing *kernelPoints, pairs []pointPair) theta4Structure {
	steps := isogenyExponent - gluingDepth
	curveEntries := curveLevels(steps)
	space := len(curveEntries) + thetaStackDepth
	levels := make([]int, space)
	top := copy(levels, curveEntries)

	// The gluing consumes the entry of level 1 above the curve entries and
	// maps them to theta points, which become the bottom of the new stack.
	domain, points := gluingIsogeny(c, gluing, pairs)
	points = append(points, make([]theta4, generators*space-len(points))...)
	top = pop(levels, top)

	return thetaChain(domain, points, levels, top, steps-1)
}

// curveLevels returns the levels of the stack entries on E for a chain of
// steps steps. A balanced strategy halves the remaining level, but pushing
// points through the gluing is expensive, so the entries stop at the first
// level below curveSaveLevel.
func curveLevels(steps int) []int {
	levels := []int{steps}

	for level := steps; level >= curveSaveLevel; {
		level -= level >> 1
		levels = append(levels, level)
	}

	return levels
}

// scalarThetaChain runs steps 2-isogeny steps from domain, with the stack of
// theta points in points, and returns the last codomain. thetaChain calls it
// when the vector code path is unavailable; vecThetaChain in
// thetavec_amd64.go mirrors it.
//
// Each step returns its codomain as an inverse dual null point. The values
// for doubling cost three projective inversions, so they are computed only
// before a step that doubles, and for the last codomain.
func scalarThetaChain(domain theta4Structure, points []theta4, levels []int, top, steps int) theta4Structure {
	var invDual theta4

	for step := range steps {
		if step > 0 && levels[top] != 1 {
			domain = newTheta4StructureFromInvDual(&invDual)
		}

		top = domain.advance(points, levels, top)
		gen1, gen2 := points[generators*top], points[generators*top+1]
		invDual = twoIsogeny4(&gen1, &gen2, points[:generators*top])
		top = pop(levels, top)
	}

	if steps == 0 {
		return domain
	}

	return newTheta4StructureFromInvDual(&invDual)
}

// pop removes the top entry of the stack after an isogeny step and returns
// the new top index.
func pop(levels []int, top int) int {
	for i := range top {
		levels[i]--
	}

	return max(top-1, 0)
}

// advance doubles the theta points on the stack until the top entry has
// level 1, and returns the new top index. advanceVec in thetavec_amd64.go
// mirrors it.
func (s *theta4Structure) advance(points []theta4, levels []int, top int) int {
	for levels[top] != 1 {
		top++

		prev := levels[top-1]
		doublings := int(thetaSplits[prev])

		for gen := range generators {
			dst := &points[generators*top+gen]
			*dst = points[generators*(top-1)+gen]
			s.doubleN(dst, doublings)
		}

		levels[top] = prev - doublings
	}

	return top
}
