// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p758

// fp2 is an element x = re + i·im of GF(p²) = GF(p)[i]/(i² + 1).
type fp2 struct{ re, im fp }

// fp2Size is the length of an encoded element of GF(p²) in bytes.
const fp2Size = 2 * fpSize

func (z *fp2) set(x *fp2) *fp2 {
	*z = *x

	return z
}

func (z *fp2) zero() {
	z.re.zero()
	z.im.zero()
}

func (z *fp2) one() *fp2 {
	z.re.one()
	z.im.zero()

	return z
}

// setUint64 sets z = v, an element of the base field.
func (z *fp2) setUint64(v uint64) *fp2 {
	z.re.setUint64(v)
	z.im.zero()

	return z
}

func (z *fp2) add(x, y *fp2) *fp2 {
	z.re.add(&x.re, &y.re)
	z.im.add(&x.im, &y.im)

	return z
}

func (z *fp2) sub(x, y *fp2) *fp2 {
	z.re.sub(&x.re, &y.re)
	z.im.sub(&x.im, &y.im)

	return z
}

func (z *fp2) neg(x *fp2) *fp2 {
	z.re.neg(&x.re)
	z.im.neg(&x.im)

	return z
}

func (z *fp2) double(x *fp2) *fp2 { return z.add(x, x) }

func (z *fp2) half(x *fp2) *fp2 {
	z.re.half(&x.re)
	z.im.half(&x.im)

	return z
}

// conjugate sets z = re − i·im, the image of x under the Frobenius map.
func (z *fp2) conjugate(x *fp2) *fp2 {
	z.re.set(&x.re)
	z.im.neg(&x.im)

	return z
}

func (z *fp2) mul(lhs, rhs *fp2) *fp2 {
	// (a + i·b)(c + i·d) = (ac − bd) + i·((a + b)(c + d) − ac − bd), where
	// reProd = ac and imProd = bd.
	var reProd, imProd, sum, rhsSum fp

	reProd.mul(&lhs.re, &rhs.re)
	imProd.mul(&lhs.im, &rhs.im)
	sum.add(&lhs.re, &lhs.im)
	rhsSum.add(&rhs.re, &rhs.im)
	sum.mul(&sum, &rhsSum)
	z.re.sub(&reProd, &imProd)
	z.im.sub(&sum, &reProd)
	z.im.sub(&z.im, &imProd)

	return z
}

func (z *fp2) square(base *fp2) *fp2 {
	// (a + i·b)² = (a + b)(a − b) + i·2ab
	var sum, diff fp

	sum.add(&base.re, &base.im)
	diff.sub(&base.re, &base.im)
	z.im.mul(&base.re, &base.im)
	z.im.double(&z.im)
	z.re.mul(&sum, &diff)

	return z
}

// squareN sets z = x^(2^n).
func (z *fp2) squareN(x *fp2, n int) {
	z.set(x)

	for range n {
		z.square(z)
	}
}

// norm returns re² + im², which lies in GF(p).
func (z *fp2) norm() fp {
	var sum, imSquared fp

	sum.square(&z.re)
	imSquared.square(&z.im)

	return *sum.add(&sum, &imSquared)
}

// invert sets z = 1/elem. If elem = 0, z is set to 0.
func (z *fp2) invert(elem *fp2) *fp2 {
	// 1/(a + i·b) = (a − i·b)/(a² + b²)
	inv := elem.norm()
	inv.invert(&inv)
	z.re.mul(&elem.re, &inv)
	z.im.mul(&elem.im, &inv)
	z.im.neg(&z.im)

	return z
}

func (z *fp2) isZero() uint64 { return z.re.isZero() & z.im.isZero() }

func (z *fp2) equal(y *fp2) uint64 { return z.re.equal(&y.re) & z.im.equal(&y.im) }

// selectFrom sets z = a if cond = 1 and z = b if cond = 0.
func (z *fp2) selectFrom(a, b *fp2, cond uint64) {
	z.re.selectFrom(&a.re, &b.re, cond)
	z.im.selectFrom(&a.im, &b.im, cond)
}

// condNeg sets z = −z if cond = 1.
func (z *fp2) condNeg(cond uint64) {
	var negated fp2

	z.selectFrom(negated.neg(z), z, cond)
}

// swap exchanges z and w if cond = 1.
func (z *fp2) swap(w *fp2, cond uint64) {
	old := *z
	z.selectFrom(w, z, cond)
	w.selectFrom(&old, w, cond)
}

// isSquare returns 1 if z is a square in GF(p²), including zero.
func (z *fp2) isSquare() uint64 {
	// z is a square in GF(p²) if and only if its norm is a square in GF(p).
	norm := z.norm()

	return norm.isSquare()
}

// sqrt sets z to a square root of elem and returns 1. The root is chosen so
// that re is even, or so that im is even when re = 0, where parity refers to
// the canonical encoding. If elem is not a square, sqrt sets z = 0 and
// returns 0.
//
// The result matches the fp2 crate used by the reference implementation.
func (z *fp2) sqrt(elem *fp2) uint64 {
	// For a root a + i·b of x0 + i·x1: a² − b² = x0 and 2ab = x1. Then
	// a² = (x0 ± √(x0² + x1²))/2, and exactly one sign gives a square in
	// GF(p) when x1 ≠ 0. When x1 = 0, the root is √x0 or i·√−x0.
	norm := elem.norm()

	var normRoot, reSquared, rootRe, rootIm, tmp fp

	success := normRoot.sqrt(&norm)

	reSquared.add(&elem.re, &normRoot)
	reSquared.half(&reSquared)

	imZero := elem.im.isZero()
	reSquared.selectFrom(&elem.re, &reSquared, imZero)

	nonSquare := 1 ^ reSquared.isSquare()
	reSquared.selectFrom(tmp.neg(&reSquared), &reSquared, nonSquare&imZero)
	reSquared.selectFrom(tmp.sub(&reSquared, &normRoot), &reSquared, nonSquare&(1^imZero))

	success &= rootRe.sqrt(&reSquared)
	tmp.double(&rootRe)
	tmp.invert(&tmp)
	rootIm.mul(&elem.im, &tmp)

	// If x1 = 0 and x0 is not a square, the root is i·√−x0.
	tmp = rootRe
	rootRe.selectFrom(&rootIm, &rootRe, nonSquare&imZero)
	rootIm.selectFrom(&tmp, &rootIm, nonSquare&imZero)

	var zero fp

	z.re.selectFrom(&rootRe, &zero, success)
	z.im.selectFrom(&rootIm, &zero, success)

	reOdd := z.re.isOdd()
	imOdd := z.im.isOdd()
	z.condNeg(reOdd | (z.re.isZero() & imOdd))

	return success
}

// bytes returns the encoding of z: the encoding of re followed by that of im.
func (z *fp2) bytes() []byte {
	return append(z.re.bytes(), z.im.bytes()...)
}

// setBytes sets z to the element encoded by enc and returns true. If enc is
// not a canonical encoding, it returns false and leaves z unchanged.
func (z *fp2) setBytes(enc []byte) bool {
	if len(enc) != fp2Size {
		return false
	}

	var value fp2
	if !value.re.setBytes(enc[:fpSize]) || !value.im.setBytes(enc[fpSize:]) {
		return false
	}

	*z = value

	return true
}

// batchInvert sets each element of elems to its inverse using a single
// inversion. All elements must be nonzero.
func batchInvert(elems []fp2) {
	if len(elems) == 0 {
		return
	}

	prefix := make([]fp2, len(elems))

	prefix[0] = elems[0]

	for i := 1; i < len(elems); i++ {
		prefix[i].mul(&prefix[i-1], &elems[i])
	}

	var inv fp2

	inv.invert(&prefix[len(elems)-1])

	for i := len(elems) - 1; i > 0; i-- {
		var elemInv fp2

		elemInv.mul(&inv, &prefix[i-1])
		inv.mul(&inv, &elems[i])
		elems[i] = elemInv
	}

	elems[0] = inv
}
