// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build amd64 && !purego

package p758

import (
	"os"
	"slices"
	"strings"
	"testing"
)

// TestHasBMI2AndADX checks the CPUID test of the assembly against the CPU
// flags that Linux reports, so that a wrong test cannot silently disable
// the assembly.
func TestHasBMI2AndADX(t *testing.T) {
	t.Parallel()

	cpuinfo, err := os.ReadFile("/proc/cpuinfo")
	if err != nil {
		t.Skipf("reading the CPU flags: %v", err)
	}

	for line := range strings.Lines(string(cpuinfo)) {
		name, value, ok := strings.Cut(line, ":")
		if !ok || strings.TrimSpace(name) != "flags" {
			continue
		}

		flags := strings.Fields(value)
		want := slices.Contains(flags, "bmi2") && slices.Contains(flags, "adx")

		if got := hasBMI2AndADX(); got != want {
			t.Fatalf("hasBMI2AndADX() = %v, but /proc/cpuinfo has flags %q", got, flags)
		}

		return
	}

	t.Skip("/proc/cpuinfo has no CPU flags")
}

// TestFpFallback runs the field and theta arithmetic with useAsm cleared, as
// on a CPU without BMI2 and ADX, so that the assembly stubs jump to the Go
// code.
//
//nolint:paralleltest // The test changes useAsm, which the parallel tests read.
func TestFpFallback(t *testing.T) {
	saved := useAsm
	useAsm = false

	t.Cleanup(func() { useAsm = saved })

	rnd := newTestRand(t.Name())
	checkMulMatchesGeneric(t, rnd, 1000)

	var point theta4
	for i := range point {
		point[i] = fromBig(t, randBig(rnd))
	}

	got, want := point, point
	theta4HadamardGeneric(&want)

	if got.hadamard(); got != want {
		t.Fatalf("hadamard(%x) = %x, want %x", point, got, want)
	}
}

// skipWithoutAsm skips a test of the assembly on a CPU that can't run it.
func skipWithoutAsm(t *testing.T) {
	t.Helper()

	if !hasBMI2AndADX() {
		t.Skip("the CPU lacks BMI2 or ADX")
	}
}

// TestFpAsm checks the assembly of GF(p) against the Go code directly.
func TestFpAsm(t *testing.T) {
	t.Parallel()
	skipWithoutAsm(t)

	rnd := newTestRand(t.Name())

	for range 1000 {
		elemX, elemY := fromBig(t, randBig(rnd)), fromBig(t, randBig(rnd))

		var got, want [fpLimbs]uint64

		fpMulGeneric(&want, &elemX.l, &elemY.l)

		if fpMulAsm(&got, &elemX.l, &elemY.l); got != want {
			t.Fatalf("fpMulAsm(%x, %x) = %x, want %x", elemX.l, elemY.l, got, want)
		}

		fpSquareGeneric(&want, &elemX.l)

		if fpSquareAsm(&got, &elemX.l); got != want {
			t.Fatalf("fpSquareAsm(%x) = %x, want %x", elemX.l, got, want)
		}
	}
}

// TestFp2Asm checks the assembly of GF(p²) against the Go code directly.
func TestFp2Asm(t *testing.T) {
	t.Parallel()
	skipWithoutAsm(t)

	rnd := newTestRand(t.Name())

	for range 1000 {
		elemX, elemY := toFp2(t, randGf2(rnd)), toFp2(t, randGf2(rnd))

		var got, want fp2

		fp2MulGeneric(&want, &elemX, &elemY)

		if fp2MulAsm(&got, &elemX, &elemY); got != want {
			t.Fatalf("fp2MulAsm(%x, %x) = %x, want %x", elemX, elemY, got, want)
		}

		fp2SquareGeneric(&want, &elemX)

		if fp2SquareAsm(&got, &elemX); got != want {
			t.Fatalf("fp2SquareAsm(%x) = %x, want %x", elemX, got, want)
		}
	}
}

// TestHadamardAsm checks the assembly of the Hadamard transform against the
// Go code directly.
func TestHadamardAsm(t *testing.T) {
	t.Parallel()
	skipWithoutAsm(t)

	rnd := newTestRand(t.Name())

	for range 100 {
		var point theta4
		for i := range point {
			point[i] = fromBig(t, randBig(rnd))
		}

		got, want := point, point
		theta4HadamardGeneric(&want)

		if theta4HadamardAsm(&got); got != want {
			t.Fatalf("theta4HadamardAsm(%x) = %x, want %x", point, got, want)
		}
	}
}
