// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build !amd64 || purego

package p758

// mul sets z = x·y and returns z.
func (z *fp) mul(x, y *fp) *fp {
	fpMulGeneric(&z.l, &x.l, &y.l)

	return z
}

// square sets z = x² and returns z.
func (z *fp) square(x *fp) *fp {
	fpSquareGeneric(&z.l, &x.l)

	return z
}

// mul sets z = x·y and returns z.
func (z *fp2) mul(x, y *fp2) *fp2 {
	fp2MulGeneric(z, x, y)

	return z
}

// square sets z = x² and returns z.
func (z *fp2) square(x *fp2) *fp2 {
	fp2SquareGeneric(z, x)

	return z
}

func theta4Hadamard(p *theta4) { theta4HadamardGeneric(p) }
