// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p758

import (
	"crypto/sha3"
	"encoding/hex"
	"errors"
	"fmt"
)

// The errors describe invalid public keys. Package mike wraps them.
var (
	ErrInvalidPublicKey     = errors.New("invalid public key")
	ErrUnsupportedPublicKey = errors.New("unsupported public key: curve is defined over GF(p)")
	ErrNotSupersingular     = errors.New("invalid public key: curve is not supersingular")
	ErrNotNormalized        = errors.New("invalid public key: curve is not in normalized form")
)

// PrivateKeySize is the length of a private key in bytes: the private key is
// an integer below 2^e.
const PrivateKeySize = (isogenyExponent + byteBits - 1) / byteBits

const (
	// A valid private key is congruent to privateKeyResidue modulo
	// privateKeyModulus.
	privateKeyModulus = 8
	privateKeyResidue = 3

	// basisOrderLog is n for the basis of E[2^n] that the shared secret
	// computation samples: the kernel generators have order 2^(e+2).
	basisOrderLog = isogenyExponent + 2

	// gluingOrderLog is n for the points of order 2^n that determine the
	// gluing kernel.
	gluingOrderLog = 5

	// weierstrassShiftDen is the denominator of A/3, the shift of x that
	// maps a Montgomery curve to short Weierstrass form.
	weierstrassShiftDen = 3
)

// startingCurve returns the starting curve E0 and the basis (x(P0), x(Q0),
// x(P0 − Q0)) of E0[2^(e+2)]. Parsing the constants costs about a
// microsecond, which is negligible next to key generation, and avoids
// package state.
func startingCurve() (curve, basisX) {
	coefA := mustFp2(startingCurveA)
	basis := basisX{
		p:  mustPointX(basisXP),
		q:  mustPointX(basisXQ),
		pq: mustPointX(basisXPQ),
	}

	return newCurve(&coefA), basis
}

// mustFp2 decodes a hex constant. It panics if the constant is invalid.
func mustFp2(hexElem string) fp2 {
	raw, err := hex.DecodeString(hexElem)
	if err != nil {
		panic(err)
	}

	var elem fp2
	if !elem.setBytes(raw) {
		panic("mike: invalid constant " + hexElem)
	}

	return elem
}

// mustPointX returns (x : 1) for the hex constant x.
func mustPointX(hexX string) pointX {
	var res pointX

	res.x = mustFp2(hexX)
	res.z.one()

	return res
}

// ClampPrivateKey turns PrivateKeySize random bytes into a valid private
// key, an integer sk < 2^e with sk ≡ 3 mod 8, by setting the fixed bits. A
// private key is valid exactly when clamping leaves it unchanged.
func ClampPrivateKey(key []byte) {
	key[len(key)-1] &= byte(1<<(isogenyExponent-byteBits*(PrivateKeySize-1))) - 1
	key[0] = key[0]&^(privateKeyModulus-1) | privateKeyResidue
}

// PublicKey returns the encoded public key for the private key priv, which
// must be valid: unchanged by ClampPrivateKey. The public key is the
// normalized codomain of the 2^e-isogeny with kernel ⟨[4](P0 + [sk]Q0)⟩,
// where sk is the integer that priv encodes.
func PublicKey(priv []byte) []byte {
	start, basis := startingCurve()
	kernel := start.threePointLadder(&basis, priv, isogenyExponent)
	codomain := start.twoIsogenyChain(&kernel, isogenyExponent)

	return codomain.a.bytes()
}

// CheckPublicKey runs the inexpensive checks on an encoded public key. See
// decodePublicKey.
func CheckPublicKey(pub []byte) error {
	_, err := decodePublicKey(pub)

	return err
}

// decodePublicKey decodes the public key pub. It rejects non-canonical
// encodings and curves defined over GF(p). Public keys are public, so the
// checks need not run in constant time.
func decodePublicKey(pub []byte) (curve, error) {
	var invalid curve

	if len(pub) != fp2Size {
		return invalid, fmt.Errorf("%w: got %d bytes, want %d", ErrInvalidPublicKey, len(pub), fp2Size)
	}

	var coefA fp2
	if !coefA.setBytes(pub) {
		return invalid, fmt.Errorf("%w: coefficient not canonically encoded below p", ErrInvalidPublicKey)
	}
	// Honest keys lie in GF(p) with negligible probability, and the gluing
	// computation does not support them. This also rejects the singular
	// curves, A = ±2.
	if coefA.im.isZero() == 1 {
		return invalid, ErrUnsupportedPublicKey
	}

	return newCurve(&coefA), nil
}

// SharedSecret returns the shared secret for the valid private key priv and
// the peer's public key pub: SHA3-256 of the MIKE invariants of the shared
// abelian fourfold. It returns an error if pub is not a supersingular curve
// in normalized form.
func SharedSecret(priv, pub []byte) ([]byte, error) {
	peer, err := decodePublicKey(pub)
	if err != nil {
		return nil, err
	}

	var aDiv3 fp2

	aDiv3.setUint64(weierstrassShiftDen).invert(&aDiv3).mul(&aDiv3, &peer.a)

	gluing, chain, err := kernel(&peer, &aDiv3, priv)
	if err != nil {
		return nil, err
	}

	codomain := peer.isogenyChain(&aDiv3, &gluing, &chain, isogenyExponent)

	var buf []byte
	for _, inv := range codomain.invariants() {
		buf = append(buf, inv.bytes()...)
	}

	secret := sha3.Sum256(buf)

	return secret[:], nil
}

// kernel returns the kernel data of the dimension-4 isogeny for the secret
// scalar sk, encoded by priv, on the peer's curve E, following Theorem 4.1
// of the MIKE paper. It also validates E, and returns an error if E is not a
// supersingular curve in normalized form. The argument aDiv3 must be A/3.
//
// From a deterministic basis (P, Q) of E[2^(e+2)] and n = (sk − 1)/2:
//
//   - the chain kernel is generated by ([n]Q + Q, [n]Q) and
//     (−[n]P − P, −[n]P), as points of E^4 (see gluing.go);
//   - the gluing kernel is the same construction for P32 = [2^(e−3)]P and
//     Q32 = [2^(e−3)]Q, which have order 32, plus the difference of the two;
//   - the diagonal and Scholten kernels are ([2]Q32, [2]P32) and ([4]P32,
//     [4]Q32).
//
// Only the steps that involve sk need to run in constant time.
func kernel(peer *curve, aDiv3 *fp2, priv []byte) (kernelPoints, [generators]pointPair, error) {
	var (
		data  kernelPoints
		chain [generators]pointPair
	)

	basis, ok := peer.torsionBasis(primeExponent-basisOrderLog, primeCofactor)
	if !ok {
		return data, chain, ErrNotSupersingular
	}

	ptP, ptQ := peer.liftBasis(&basis)
	p32 := peer.doubleNFast(&ptP, aDiv3, basisOrderLog-gluingOrderLog)
	q32 := peer.doubleNFast(&ptQ, aDiv3, basisOrderLog-gluingOrderLog)
	p16 := peer.double(&p32)
	q16 := peer.double(&q32)
	data.diagonal = [2]point{q16, p16}

	data.scholten = [2]point{peer.double(&p16), peer.double(&q16)}

	err := checkPublicKey(peer, &data.scholten[0], &data.scholten[1])
	if err != nil {
		return data, chain, err
	}

	// Multiplying with start = 1 skips the lowest bit of the odd scalar sk,
	// which yields [n]P.
	np := peer.mul(&ptP, priv, 1, isogenyExponent)
	nq := peer.mul(&ptQ, priv, 1, isogenyExponent)
	t1 := peer.add(&nq, &ptQ)
	t3 := peer.add(&np, &ptP)
	chain = [generators]pointPair{{t1, nq}, {t3.neg(), np.neg()}}

	// P32 and Q32 have order 32, so only the low bits of n matter.
	np32 := peer.mul(&p32, priv, 1, gluingOrderLog+1)
	nq32 := peer.mul(&q32, priv, 1, gluingOrderLog+1)
	g1 := peer.add(&nq32, &q32)
	g3 := peer.add(&np32, &p32)
	data.gluing = [3][2]point{
		{g1, nq32},
		{g3.neg(), np32.neg()},
		{peer.sub(&g1, &g3), peer.sub(&nq32, &np32)},
	}

	return data, chain, nil
}

// checkPublicKey checks that the curve peer is supersingular and in
// normalized form, given the Scholten kernel points P8 and Q8 sampled from
// it.
//
// P8 and Q8 are the multiples of the two sampled points by c·2^(f−3). They
// have order exactly 8, with [4]P8 ≠ [4]Q8, only if the sampled points
// generate all of E[2^f], so that E[2^f] is GF(p²)-rational. Because
// 2^(f−2) ≥ c, the Hasse bound then leaves (p + 1)² as the only possible
// number of points, so the curve is supersingular (Section 4.2 of the MIKE
// paper).
func checkPublicKey(peer *curve, p8, q8 *point) error {
	ord4P := peer.double(p8)
	ord2P := peer.double(&ord4P)
	ord4Q := peer.double(q8)
	ord2Q := peer.double(&ord4Q)
	// [4]P8 and [4]Q8 must have order 2, that is y = 0 and z ≠ 0. The
	// gluing also requires [4]Q8 = (0, 0). If [4]P8 were (0, 0) too, then
	// [2]P8 would have x = ±1, and the normalization below would fail.
	order8 := ord2P.y.isZero() & (1 ^ ord2P.isInfinity()) &
		ord2Q.y.isZero() & (1 ^ ord2Q.isInfinity()) & ord2Q.x.isZero()
	if order8 == 0 {
		return ErrNotSupersingular
	}
	// Key generation outputs normalized curves, and [2]P8 has order 4, so
	// normalizing from it must give back the same curve.
	ord4X := ord4P.toX()
	if normalized := normalizeCurve(&ord4X); normalized.a.equal(&peer.a) == 0 {
		return ErrNotNormalized
	}

	return nil
}
