// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build goexperiment.simd

package p758

import "simd/archsimd"

// This file runs the 2-isogeny steps of the dimension-4 chain with AVX2.
// Doubling a theta point and mapping it through an isogeny apply the same
// operation to all 16 coordinates, so a point fits in four vfp values, and
// the results equal those of the scalar code.

// thetaChain runs steps 2-isogeny steps from domain, with the stack of theta
// points in points, and returns the last codomain. It uses AVX2 if the CPU
// supports it.
func thetaChain(domain theta4Structure, points []theta4, levels []int, top, steps int) theta4Structure {
	if !archsimd.X86.AVX2() {
		return scalarThetaChain(domain, points, levels, top, steps)
	}

	return vecThetaChain(domain, points, levels, top, steps)
}

// Each vector multiplication introduces a factor ρ = R/R_v. A sequence of
// them multiplies one of its constants by the power of ρ⁻¹ that cancels the
// factors: the number of multiplications in the sequence.
const (
	doubleMuls = 5 // in vtheta4Structure.double
	imageMuls  = 2 // in each image of twoIsogeny4Vec
)

// vecRhoInvPow returns ρ⁻ⁿ in Montgomery form, for n ≥ 1.
func vecRhoInvPow(n int) fp {
	rhoInv := fp{fpVecRhoInv}
	res := rhoInv

	for range n - 1 {
		res.mul(&res, &rhoInv)
	}

	return res
}

// vtheta4 is a theta4 point in vector form: lane l of p[g] holds coordinate
// 4g + l. Between operations, its coordinates are normalized and below 48p.
type vtheta4 [4]vfp

func (p *vtheta4) set(src *theta4) {
	for g := range p {
		p[g].set((*[4]fp)(src[4*g:]))
	}
}

// scaled returns the point p, with each coordinate multiplied by k with one
// vector multiplication: the result is p·k·ρ, and k = ρ⁻¹ returns p itself.
func (p *vtheta4) scaled(k *fp) theta4 {
	var factor vfp

	factor.broadcast(k)

	var res theta4

	for g := range p {
		var prod vfp

		prod.mul(&p[g], &factor)
		elems := prod.elements()
		copy(res[4*g:], elems[:])
	}

	return res
}

func (p *vtheta4) square() {
	for g := range p {
		p[g].square(&p[g])
	}
}

// mulCoords multiplies p coordinate-wise by q.
func (p *vtheta4) mulCoords(q *vtheta4) {
	for g := range p {
		p[g].mul(&p[g], &q[g])
	}
}

// hadamard applies the Hadamard transform in place. It takes coordinates
// below 2p and returns coordinates below 48p.
//
// Each output is a signed sum of the 16 inputs, with at most 8 negative
// terms, so it lies in (−16p, 32p). The transform adds and subtracts limbs
// without carries, treating them as signed values, then adds 16p and
// normalizes.
func (p *vtheta4) hadamard() {
	for limb := range vecLimbs {
		vec0, vec1, vec2, vec3 := p[0][limb], p[1][limb], p[2][limb], p[3][limb]

		// Butterflies between vectors: coordinates 4g + l and 4(g^1) + l,
		// then 4g + l and 4(g^2) + l.
		vec0, vec1 = vec0.Add(vec1), vec0.Sub(vec1)
		vec2, vec3 = vec2.Add(vec3), vec2.Sub(vec3)
		vec0, vec2 = vec0.Add(vec2), vec0.Sub(vec2)
		vec1, vec3 = vec1.Add(vec3), vec1.Sub(vec3)

		vec0, vec1 = butterflyLanes(vec0, vec1)
		vec2, vec3 = butterflyLanes(vec2, vec3)

		offset := archsimd.BroadcastUint64x4(vecOffset[limb])
		p[0][limb] = vec0.Add(offset)
		p[1][limb] = vec1.Add(offset)
		p[2][limb] = vec2.Add(offset)
		p[3][limb] = vec3.Add(offset)
	}

	for g := range p {
		p[g].normalize()
	}
}

// The 128-bit halves that x.ConcatPermute128Scalars(lo, hi, y) selects.
const (
	lowOfX  = 0
	highOfX = 1
	lowOfY  = 2
	highOfY = 3
)

// butterflyLanes applies the butterflies between the lanes of a vector, to
// lhs and to rhs: lanes l and l^1, then lanes l and l^2.
func butterflyLanes(lhs, rhs archsimd.Uint64x4) (archsimd.Uint64x4, archsimd.Uint64x4) {
	// even = (lhs0, rhs0, lhs2, rhs2) and odd = (lhs1, rhs1, lhs3, rhs3).
	even, odd := lhs.InterleaveLoGrouped(rhs), lhs.InterleaveHiGrouped(rhs)
	sum, diff := even.Add(odd), even.Sub(odd)
	lhs, rhs = sum.InterleaveLoGrouped(diff), sum.InterleaveHiGrouped(diff)

	// low = (lhs0, lhs1, rhs0, rhs1) and high = (lhs2, lhs3, rhs2, rhs3).
	low := lhs.ConcatPermute128Scalars(lowOfX, lowOfY, rhs)
	high := lhs.ConcatPermute128Scalars(highOfX, highOfY, rhs)
	sum, diff = low.Add(high), low.Sub(high)

	return sum.ConcatPermute128Scalars(lowOfX, lowOfY, diff), sum.ConcatPermute128Scalars(highOfX, highOfY, diff)
}

// vtheta4Structure holds the constants of a theta4Structure for doubling
// points in vector form.
type vtheta4Structure struct {
	invNull   vtheta4
	invDualSq vtheta4 // multiplied by ρ^−doubleMuls; see double
}

func newVtheta4Structure(src *theta4Structure) vtheta4Structure {
	rhoInv := vecRhoInvPow(doubleMuls)

	var invDualSq theta4
	for i := range invDualSq {
		invDualSq[i].mul(&src.invDualSq[i], &rhoInv)
	}

	var res vtheta4Structure

	res.invNull.set(&src.invNull)
	res.invDualSq.set(&invDualSq)

	return res
}

// double sets dst = [2]dst, as theta4Structure.double does. Its
// doubleMuls multiplications introduce ρ^doubleMuls, which invDualSq
// cancels.
func (s *vtheta4Structure) double(dst *vtheta4) {
	dst.square()
	dst.hadamard()
	dst.square()
	dst.mulCoords(&s.invDualSq)
	dst.hadamard()
	dst.mulCoords(&s.invNull)
}

// advanceVec is theta4Structure.advance for points in vector form, on the
// theta structure domain. It follows the same strategy.
func advanceVec(domain *theta4Structure, points []vtheta4, levels []int, top int) int {
	if levels[top] == 1 {
		return top
	}

	vecDomain := newVtheta4Structure(domain)

	for levels[top] != 1 {
		top++

		prev := levels[top-1]
		doublings := int(thetaSplits[prev])

		for gen := range generators {
			dst := &points[generators*top+gen]
			*dst = points[generators*(top-1)+gen]

			for range doublings {
				vecDomain.double(dst)
			}
		}

		levels[top] = prev - doublings
	}

	return top
}

// vecThetaChain is scalarThetaChain with the theta points in vector form.
func vecThetaChain(domain theta4Structure, points []theta4, levels []int, top, steps int) theta4Structure {
	vecPoints := make([]vtheta4, len(points))
	for idx := range points {
		vecPoints[idx].set(&points[idx])
	}

	var invDual theta4

	for step := range steps {
		if step > 0 && levels[top] != 1 {
			domain = newTheta4StructureFromInvDual(&invDual)
		}

		top = advanceVec(&domain, vecPoints, levels, top)
		invDual = twoIsogeny4Vec(&vecPoints[generators*top], &vecPoints[generators*top+1], vecPoints[:generators*top])
		top = pop(levels, top)
	}

	if steps == 0 {
		return domain
	}

	return newTheta4StructureFromInvDual(&invDual)
}

// twoIsogeny4Vec is twoIsogeny4 for points in vector form.
func twoIsogeny4Vec(gen1, gen2 *vtheta4, images []vtheta4) theta4 {
	rhoInv := vecRhoInvPow(imageMuls)

	// The kernel points also take imageMuls multiplications: the square and
	// the one in scaled.
	kerP, kerQ := *gen1, *gen2
	kerP.square()
	kerP.hadamard()
	kerQ.square()
	kerQ.hadamard()
	scaledP, scaledQ := kerP.scaled(&rhoInv), kerQ.scaled(&rhoInv)
	invDual := invDualCodomain(&scaledP, &scaledQ)

	var scaledInvDual theta4
	for i := range scaledInvDual {
		scaledInvDual[i].mul(&invDual[i], &rhoInv)
	}

	var vecInvDual vtheta4

	vecInvDual.set(&scaledInvDual)

	for idx := range images {
		img := &images[idx]
		img.square()
		img.hadamard()
		img.mulCoords(&vecInvDual)
		img.hadamard()
	}

	return invDual
}
