// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

// Package p566 implements MIKE for the parameter set in params.go. All
// per-prime packages share this code, which internal/gen copies from one
// source.
package p566
