// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p566

// fp2 is an element x = re + i·im of GF(p²) = GF(p)[i]/(i² + 1).
type fp2 struct{ re, im fp }

// fp2Size is the length of an encoded element of GF(p²) in bytes.
const fp2Size = 2 * fpSize

func (z *fp2) set(x *fp2) *fp2 {
	*z = *x

	return z
}

func (z *fp2) zero() {
	z.re.zero()
	z.im.zero()
}

func (z *fp2) one() *fp2 {
	z.re.one()
	z.im.zero()

	return z
}

// setUint64 sets z = v, an element of the base field.
func (z *fp2) setUint64(v uint64) *fp2 {
	z.re.setUint64(v)
	z.im.zero()

	return z
}

func (z *fp2) add(x, y *fp2) *fp2 {
	z.re.add(&x.re, &y.re)
	z.im.add(&x.im, &y.im)

	return z
}

func (z *fp2) sub(x, y *fp2) *fp2 {
	z.re.sub(&x.re, &y.re)
	z.im.sub(&x.im, &y.im)

	return z
}

func (z *fp2) neg(x *fp2) *fp2 {
	z.re.neg(&x.re)
	z.im.neg(&x.im)

	return z
}

func (z *fp2) double(x *fp2) *fp2 { return z.add(x, x) }

func (z *fp2) half(x *fp2) *fp2 {
	z.re.half(&x.re)
	z.im.half(&x.im)

	return z
}

// conjugate sets z = re − i·im, the image of x under the Frobenius map.
func (z *fp2) conjugate(x *fp2) *fp2 {
	z.re.set(&x.re)
	z.im.neg(&x.im)

	return z
}

// fp2MulGeneric sets out = lhs·rhs. The mul method calls it, or assembly on
// amd64.
func fp2MulGeneric(out, lhs, rhs *fp2) {
	// (a + i·b)(c + i·d) = (ac − bd) + i·((a + b)(c + d) − ac − bd), where
	// reProd = ac and imProd = bd.
	var reProd, imProd, sum, rhsSum fp

	reProd.mul(&lhs.re, &rhs.re)
	imProd.mul(&lhs.im, &rhs.im)
	sum.add(&lhs.re, &lhs.im)
	rhsSum.add(&rhs.re, &rhs.im)
	sum.mul(&sum, &rhsSum)
	out.re.sub(&reProd, &imProd)
	out.im.sub(&sum, &reProd)
	out.im.sub(&out.im, &imProd)
}

// fp2SquareGeneric sets out = base². The square method calls it, or assembly
// on amd64.
func fp2SquareGeneric(out, base *fp2) {
	// (a + i·b)² = (a + b)(a − b) + i·2ab
	var sum, diff fp

	sum.add(&base.re, &base.im)
	diff.sub(&base.re, &base.im)
	out.im.mul(&base.re, &base.im)
	out.im.double(&out.im)
	out.re.mul(&sum, &diff)
}

// squareN sets z = x^(2^n).
func (z *fp2) squareN(x *fp2, n int) {
	z.set(x)

	for range n {
		z.square(z)
	}
}

// norm returns re² + im², which lies in GF(p).
func (z *fp2) norm() fp {
	var sum, imSquared fp

	sum.square(&z.re)
	imSquared.square(&z.im)

	return *sum.add(&sum, &imSquared)
}

// invert sets z = 1/elem. If elem = 0, z is set to 0.
func (z *fp2) invert(elem *fp2) *fp2 {
	// 1/(a + i·b) = (a − i·b)/(a² + b²)
	inv := elem.norm()
	inv.invert(&inv)
	z.re.mul(&elem.re, &inv)
	z.im.mul(&elem.im, &inv)
	z.im.neg(&z.im)

	return z
}

func (z *fp2) isZero() uint64 { return z.re.isZero() & z.im.isZero() }

func (z *fp2) equal(y *fp2) uint64 { return z.re.equal(&y.re) & z.im.equal(&y.im) }

// selectFrom sets z = a if cond = 1 and z = b if cond = 0.
func (z *fp2) selectFrom(a, b *fp2, cond uint64) {
	z.re.selectFrom(&a.re, &b.re, cond)
	z.im.selectFrom(&a.im, &b.im, cond)
}

// condNeg sets z = −z if cond = 1.
func (z *fp2) condNeg(cond uint64) {
	var negated fp2

	z.selectFrom(negated.neg(z), z, cond)
}

// swap exchanges z and w if cond = 1.
func (z *fp2) swap(w *fp2, cond uint64) {
	old := *z
	z.selectFrom(w, z, cond)
	w.selectFrom(&old, w, cond)
}

// isSquare returns 1 if z is a square in GF(p²), including zero.
func (z *fp2) isSquare() uint64 {
	// z is a square in GF(p²) if and only if its norm is a square in GF(p).
	norm := z.norm()

	return norm.isSquare()
}

// sqrt sets z to a square root of elem and returns 1. The root is chosen so
// that re is even, or so that im is even when re = 0, where parity refers to
// the canonical encoding. If elem is not a square, sqrt sets z = 0 and
// returns 0.
//
// The result matches the fp2 crate used by the reference implementation.
func (z *fp2) sqrt(elem *fp2) uint64 {
	// The method of Aardal et al. (https://eprint.iacr.org/2024/1563), for
	// p ≡ 3 mod 4. For a root a + i·b of x0 + i·x1, a² = (x0 + δ)/2 for a
	// square root δ of x0² + x1². With t = 2(x0 + δ) and s = t^((p−3)/4),
	// the root is (x0 + δ)·s + i·x1·s if t is a square, and
	// x1·s − i·(x0 + δ)·s otherwise.
	norm := elem.norm()

	var delta, sum, twice, scale, check fp

	delta.pow(&norm, &fpExpSqrt)
	// If x1 = 0, δ may be −x0, which would make the sum zero, so take
	// δ = x0 instead.
	delta.selectFrom(&elem.re, &delta, elem.im.isZero())
	sum.add(&elem.re, &delta)
	twice.double(&sum)
	scale.pow(&twice, &fpExpRsqrt)

	var root, other fp2

	root.re.mul(&sum, &scale)
	root.im.mul(&elem.im, &scale)
	other.re = root.im
	other.im.neg(&root.re)

	tIsSquare := check.double(&root.re).square(&check).equal(&twice)
	root.selectFrom(&root, &other, tIsSquare)

	var zero, squared fp2

	success := squared.square(&root).equal(elem)
	z.selectFrom(&root, &zero, success)

	reOdd := z.re.isOdd()
	imOdd := z.im.isOdd()
	z.condNeg(reOdd | (z.re.isZero() & imOdd))

	return success
}

// bytes returns the encoding of z: the encoding of re followed by that of im.
func (z *fp2) bytes() []byte {
	return append(z.re.bytes(), z.im.bytes()...)
}

// setBytes sets z to the element encoded by enc and returns true. If enc is
// not a canonical encoding, it returns false and leaves z unchanged.
func (z *fp2) setBytes(enc []byte) bool {
	if len(enc) != fp2Size {
		return false
	}

	var value fp2
	if !value.re.setBytes(enc[:fpSize]) || !value.im.setBytes(enc[fpSize:]) {
		return false
	}

	*z = value

	return true
}

// batchInvert sets each element of elems to its inverse using a single
// inversion. All elements must be nonzero.
func batchInvert(elems []fp2) {
	if len(elems) == 0 {
		return
	}

	prefix := make([]fp2, len(elems))

	prefix[0] = elems[0]

	for i := 1; i < len(elems); i++ {
		prefix[i].mul(&prefix[i-1], &elems[i])
	}

	var inv fp2

	inv.invert(&prefix[len(elems)-1])

	for i := len(elems) - 1; i > 0; i-- {
		var elemInv fp2

		elemInv.mul(&inv, &prefix[i-1])
		inv.mul(&inv, &elems[i])
		elems[i] = elemInv
	}

	elems[0] = inv
}
