// Code generated by internal/gen. DO NOT EDIT.

package p566

import "math/bits"

// Field constants for p = 77·2^566 − 1, a 573-bit prime. Elements
// use 9 limbs, and R = 2^(64·9) is the Montgomery constant.
const (
	fpLimbs = 9
	fpSize  = 72 // the length of an encoded element in bytes

	fpPTop = 0x1340000000000000 // the top limb of p + 1; the other limbs are zero
)

var (
	fpP       = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x133fffffffffffff}
	fpR       = [fpLimbs]uint64{0x000000000000000d, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x05c0000000000000}
	fpR2      = [fpLimbs]uint64{0x31dec0d4c77b0403, 0x531dec0d4c77b035, 0x3531dec0d4c77b03, 0x03531dec0d4c77b0, 0xb03531dec0d4c77b, 0x7b03531dec0d4c77, 0x77b03531dec0d4c7, 0xc77b03531dec0d4c, 0x12b7b03531dec0d4}
	fpExpInv  = [fpLimbs]uint64{0xfffffffffffffffd, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x133fffffffffffff} // p − 2
	fpExpSqrt = [fpLimbs]uint64{0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x04d0000000000000} // (p + 1)/4
	fpExpLeg  = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x099fffffffffffff} // (p − 1)/2

	// fpExpRsqrt is (p − 3)/4: x^((p − 3)/4) is 1/√x for a square x.
	fpExpRsqrt = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x04cfffffffffffff}

	fpThird = [fpLimbs]uint64{0xaaaaaaaaaaaaaaaf, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0xaaaaaaaaaaaaaaaa, 0x01eaaaaaaaaaaaaa} // 1/3 in Montgomery form

	// fpNonSquareSteps holds, in increasing order, the first integers h ≥ 1
	// for which 1 + h² is not a square in GF(p).
	fpNonSquareSteps = [...]uint16{
		2, 3, 4, 5, 6, 9, 10, 11, 15, 18, 20, 23, 25, 26, 27, 28,
		30, 32, 33, 35, 36, 37, 38, 43, 44, 46, 47, 51, 54, 65, 66, 67,
		70, 72, 73, 77, 79, 80, 81, 85, 97, 98, 99, 101, 103, 105, 106, 107,
		108, 114, 116, 117, 118, 119, 120, 122, 123, 124, 126, 127, 128, 131, 133, 136,
		137, 138, 139, 141, 145, 146, 149, 150, 156, 160, 163, 164, 166, 168, 170, 171,
		172, 175, 177, 179, 180, 181, 186, 188, 190, 191, 193, 195, 196, 197, 198, 206,
		210, 211, 212, 213, 216, 217, 218, 221, 223, 224, 226, 228, 229, 231, 232, 233,
		236, 238, 241, 242, 243, 244, 247, 248, 255, 258, 259, 260, 261, 267, 268, 271,
	}
)

// add sets z = x + y and returns z.
func (z *fp) add(x, y *fp) *fp {
	var c, b uint64
	t0, c := bits.Add64(x.l[0], y.l[0], 0)
	t1, c := bits.Add64(x.l[1], y.l[1], c)
	t2, c := bits.Add64(x.l[2], y.l[2], c)
	t3, c := bits.Add64(x.l[3], y.l[3], c)
	t4, c := bits.Add64(x.l[4], y.l[4], c)
	t5, c := bits.Add64(x.l[5], y.l[5], c)
	t6, c := bits.Add64(x.l[6], y.l[6], c)
	t7, c := bits.Add64(x.l[7], y.l[7], c)
	t8, c := bits.Add64(x.l[8], y.l[8], c)
	t0, b = bits.Sub64(t0, 0xffffffffffffffff, 0)
	t1, b = bits.Sub64(t1, 0xffffffffffffffff, b)
	t2, b = bits.Sub64(t2, 0xffffffffffffffff, b)
	t3, b = bits.Sub64(t3, 0xffffffffffffffff, b)
	t4, b = bits.Sub64(t4, 0xffffffffffffffff, b)
	t5, b = bits.Sub64(t5, 0xffffffffffffffff, b)
	t6, b = bits.Sub64(t6, 0xffffffffffffffff, b)
	t7, b = bits.Sub64(t7, 0xffffffffffffffff, b)
	t8, b = bits.Sub64(t8, fpPTop-1, b)
	mask := -b
	z.l[0], c = bits.Add64(t0, mask, 0)
	z.l[1], c = bits.Add64(t1, mask, c)
	z.l[2], c = bits.Add64(t2, mask, c)
	z.l[3], c = bits.Add64(t3, mask, c)
	z.l[4], c = bits.Add64(t4, mask, c)
	z.l[5], c = bits.Add64(t5, mask, c)
	z.l[6], c = bits.Add64(t6, mask, c)
	z.l[7], c = bits.Add64(t7, mask, c)
	z.l[8], c = bits.Add64(t8, (fpPTop-1)&mask, c)
	return z
}

// sub sets z = x − y and returns z.
func (z *fp) sub(x, y *fp) *fp {
	var b, c uint64
	t0, b := bits.Sub64(x.l[0], y.l[0], 0)
	t1, b := bits.Sub64(x.l[1], y.l[1], b)
	t2, b := bits.Sub64(x.l[2], y.l[2], b)
	t3, b := bits.Sub64(x.l[3], y.l[3], b)
	t4, b := bits.Sub64(x.l[4], y.l[4], b)
	t5, b := bits.Sub64(x.l[5], y.l[5], b)
	t6, b := bits.Sub64(x.l[6], y.l[6], b)
	t7, b := bits.Sub64(x.l[7], y.l[7], b)
	t8, b := bits.Sub64(x.l[8], y.l[8], b)
	mask := -b
	z.l[0], c = bits.Add64(t0, mask, 0)
	z.l[1], c = bits.Add64(t1, mask, c)
	z.l[2], c = bits.Add64(t2, mask, c)
	z.l[3], c = bits.Add64(t3, mask, c)
	z.l[4], c = bits.Add64(t4, mask, c)
	z.l[5], c = bits.Add64(t5, mask, c)
	z.l[6], c = bits.Add64(t6, mask, c)
	z.l[7], c = bits.Add64(t7, mask, c)
	z.l[8], c = bits.Add64(t8, (fpPTop-1)&mask, c)
	return z
}

// fpMulGeneric sets z = x·y/R mod p. The inputs must be below p, and z may
// alias them.
func fpMulGeneric(z, x, y *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9 uint64
	var h0, h1, h2, h3, h4, h5, h6, h7, h8 uint64
	var l0, l1, l2, l3, l4, l5, l6, l7, l8 uint64
	var r0, r1, r2, r3, r4, r5, r6, r7, r8, r9 uint64
	// Row 0: t += x·y[0].
	h0, l0 = bits.Mul64(x[0], y[0])
	h1, l1 = bits.Mul64(x[1], y[0])
	h2, l2 = bits.Mul64(x[2], y[0])
	h3, l3 = bits.Mul64(x[3], y[0])
	h4, l4 = bits.Mul64(x[4], y[0])
	h5, l5 = bits.Mul64(x[5], y[0])
	h6, l6 = bits.Mul64(x[6], y[0])
	h7, l7 = bits.Mul64(x[7], y[0])
	h8, l8 = bits.Mul64(x[8], y[0])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 1: t += x·y[1].
	h0, l0 = bits.Mul64(x[0], y[1])
	h1, l1 = bits.Mul64(x[1], y[1])
	h2, l2 = bits.Mul64(x[2], y[1])
	h3, l3 = bits.Mul64(x[3], y[1])
	h4, l4 = bits.Mul64(x[4], y[1])
	h5, l5 = bits.Mul64(x[5], y[1])
	h6, l6 = bits.Mul64(x[6], y[1])
	h7, l7 = bits.Mul64(x[7], y[1])
	h8, l8 = bits.Mul64(x[8], y[1])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 2: t += x·y[2].
	h0, l0 = bits.Mul64(x[0], y[2])
	h1, l1 = bits.Mul64(x[1], y[2])
	h2, l2 = bits.Mul64(x[2], y[2])
	h3, l3 = bits.Mul64(x[3], y[2])
	h4, l4 = bits.Mul64(x[4], y[2])
	h5, l5 = bits.Mul64(x[5], y[2])
	h6, l6 = bits.Mul64(x[6], y[2])
	h7, l7 = bits.Mul64(x[7], y[2])
	h8, l8 = bits.Mul64(x[8], y[2])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 3: t += x·y[3].
	h0, l0 = bits.Mul64(x[0], y[3])
	h1, l1 = bits.Mul64(x[1], y[3])
	h2, l2 = bits.Mul64(x[2], y[3])
	h3, l3 = bits.Mul64(x[3], y[3])
	h4, l4 = bits.Mul64(x[4], y[3])
	h5, l5 = bits.Mul64(x[5], y[3])
	h6, l6 = bits.Mul64(x[6], y[3])
	h7, l7 = bits.Mul64(x[7], y[3])
	h8, l8 = bits.Mul64(x[8], y[3])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 4: t += x·y[4].
	h0, l0 = bits.Mul64(x[0], y[4])
	h1, l1 = bits.Mul64(x[1], y[4])
	h2, l2 = bits.Mul64(x[2], y[4])
	h3, l3 = bits.Mul64(x[3], y[4])
	h4, l4 = bits.Mul64(x[4], y[4])
	h5, l5 = bits.Mul64(x[5], y[4])
	h6, l6 = bits.Mul64(x[6], y[4])
	h7, l7 = bits.Mul64(x[7], y[4])
	h8, l8 = bits.Mul64(x[8], y[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 5: t += x·y[5].
	h0, l0 = bits.Mul64(x[0], y[5])
	h1, l1 = bits.Mul64(x[1], y[5])
	h2, l2 = bits.Mul64(x[2], y[5])
	h3, l3 = bits.Mul64(x[3], y[5])
	h4, l4 = bits.Mul64(x[4], y[5])
	h5, l5 = bits.Mul64(x[5], y[5])
	h6, l6 = bits.Mul64(x[6], y[5])
	h7, l7 = bits.Mul64(x[7], y[5])
	h8, l8 = bits.Mul64(x[8], y[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 6: t += x·y[6].
	h0, l0 = bits.Mul64(x[0], y[6])
	h1, l1 = bits.Mul64(x[1], y[6])
	h2, l2 = bits.Mul64(x[2], y[6])
	h3, l3 = bits.Mul64(x[3], y[6])
	h4, l4 = bits.Mul64(x[4], y[6])
	h5, l5 = bits.Mul64(x[5], y[6])
	h6, l6 = bits.Mul64(x[6], y[6])
	h7, l7 = bits.Mul64(x[7], y[6])
	h8, l8 = bits.Mul64(x[8], y[6])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 7: t += x·y[7].
	h0, l0 = bits.Mul64(x[0], y[7])
	h1, l1 = bits.Mul64(x[1], y[7])
	h2, l2 = bits.Mul64(x[2], y[7])
	h3, l3 = bits.Mul64(x[3], y[7])
	h4, l4 = bits.Mul64(x[4], y[7])
	h5, l5 = bits.Mul64(x[5], y[7])
	h6, l6 = bits.Mul64(x[6], y[7])
	h7, l7 = bits.Mul64(x[7], y[7])
	h8, l8 = bits.Mul64(x[8], y[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	// Row 8: t += x·y[8].
	h0, l0 = bits.Mul64(x[0], y[8])
	h1, l1 = bits.Mul64(x[1], y[8])
	h2, l2 = bits.Mul64(x[2], y[8])
	h3, l3 = bits.Mul64(x[3], y[8])
	h4, l4 = bits.Mul64(x[4], y[8])
	h5, l5 = bits.Mul64(x[5], y[8])
	h6, l6 = bits.Mul64(x[6], y[8])
	h7, l7 = bits.Mul64(x[7], y[8])
	h8, l8 = bits.Mul64(x[8], y[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, c = bits.Add64(l8, h7, c)
	r9, _ = bits.Add64(h8, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	t9, c = bits.Add64(t9, r9, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = t9
	t9 = 0
	t7, c = bits.Add64(t7, l0, 0)
	t8, _ = bits.Add64(t8, h0, c)
	var b uint64
	t0, b = bits.Sub64(t0, 0xffffffffffffffff, 0)
	t1, b = bits.Sub64(t1, 0xffffffffffffffff, b)
	t2, b = bits.Sub64(t2, 0xffffffffffffffff, b)
	t3, b = bits.Sub64(t3, 0xffffffffffffffff, b)
	t4, b = bits.Sub64(t4, 0xffffffffffffffff, b)
	t5, b = bits.Sub64(t5, 0xffffffffffffffff, b)
	t6, b = bits.Sub64(t6, 0xffffffffffffffff, b)
	t7, b = bits.Sub64(t7, 0xffffffffffffffff, b)
	t8, b = bits.Sub64(t8, fpPTop-1, b)
	mask := -b
	z[0], c = bits.Add64(t0, mask, 0)
	z[1], c = bits.Add64(t1, mask, c)
	z[2], c = bits.Add64(t2, mask, c)
	z[3], c = bits.Add64(t3, mask, c)
	z[4], c = bits.Add64(t4, mask, c)
	z[5], c = bits.Add64(t5, mask, c)
	z[6], c = bits.Add64(t6, mask, c)
	z[7], c = bits.Add64(t7, mask, c)
	z[8], c = bits.Add64(t8, (fpPTop-1)&mask, c)
}

// fpSquareGeneric sets z = x²/R mod p. The input must be below p, and z may
// alias it.
func fpSquareGeneric(z, x *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17 uint64
	var h0, h1, h2, h3, h4, h5, h6, h7, h8 uint64
	var l0, l1, l2, l3, l4, l5, l6, l7, l8 uint64
	var r0, r1, r2, r3, r4, r5, r6, r7, r8 uint64
	// Cross products with x[0].
	h0, l0 = bits.Mul64(x[0], x[1])
	h1, l1 = bits.Mul64(x[0], x[2])
	h2, l2 = bits.Mul64(x[0], x[3])
	h3, l3 = bits.Mul64(x[0], x[4])
	h4, l4 = bits.Mul64(x[0], x[5])
	h5, l5 = bits.Mul64(x[0], x[6])
	h6, l6 = bits.Mul64(x[0], x[7])
	h7, l7 = bits.Mul64(x[0], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t1, c = bits.Add64(t1, r0, 0)
	t2, c = bits.Add64(t2, r1, c)
	t3, c = bits.Add64(t3, r2, c)
	t4, c = bits.Add64(t4, r3, c)
	t5, c = bits.Add64(t5, r4, c)
	t6, c = bits.Add64(t6, r5, c)
	t7, c = bits.Add64(t7, r6, c)
	t8, c = bits.Add64(t8, r7, c)
	t9, c = bits.Add64(t9, r8, c)
	t10 = c
	// Cross products with x[1].
	h0, l0 = bits.Mul64(x[1], x[2])
	h1, l1 = bits.Mul64(x[1], x[3])
	h2, l2 = bits.Mul64(x[1], x[4])
	h3, l3 = bits.Mul64(x[1], x[5])
	h4, l4 = bits.Mul64(x[1], x[6])
	h5, l5 = bits.Mul64(x[1], x[7])
	h6, l6 = bits.Mul64(x[1], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, _ = bits.Add64(h6, 0, c)
	t3, c = bits.Add64(t3, r0, 0)
	t4, c = bits.Add64(t4, r1, c)
	t5, c = bits.Add64(t5, r2, c)
	t6, c = bits.Add64(t6, r3, c)
	t7, c = bits.Add64(t7, r4, c)
	t8, c = bits.Add64(t8, r5, c)
	t9, c = bits.Add64(t9, r6, c)
	t10, c = bits.Add64(t10, r7, c)
	t11 = c
	// Cross products with x[2].
	h0, l0 = bits.Mul64(x[2], x[3])
	h1, l1 = bits.Mul64(x[2], x[4])
	h2, l2 = bits.Mul64(x[2], x[5])
	h3, l3 = bits.Mul64(x[2], x[6])
	h4, l4 = bits.Mul64(x[2], x[7])
	h5, l5 = bits.Mul64(x[2], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t5, c = bits.Add64(t5, r0, 0)
	t6, c = bits.Add64(t6, r1, c)
	t7, c = bits.Add64(t7, r2, c)
	t8, c = bits.Add64(t8, r3, c)
	t9, c = bits.Add64(t9, r4, c)
	t10, c = bits.Add64(t10, r5, c)
	t11, c = bits.Add64(t11, r6, c)
	t12 = c
	// Cross products with x[3].
	h0, l0 = bits.Mul64(x[3], x[4])
	h1, l1 = bits.Mul64(x[3], x[5])
	h2, l2 = bits.Mul64(x[3], x[6])
	h3, l3 = bits.Mul64(x[3], x[7])
	h4, l4 = bits.Mul64(x[3], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t7, c = bits.Add64(t7, r0, 0)
	t8, c = bits.Add64(t8, r1, c)
	t9, c = bits.Add64(t9, r2, c)
	t10, c = bits.Add64(t10, r3, c)
	t11, c = bits.Add64(t11, r4, c)
	t12, c = bits.Add64(t12, r5, c)
	t13 = c
	// Cross products with x[4].
	h0, l0 = bits.Mul64(x[4], x[5])
	h1, l1 = bits.Mul64(x[4], x[6])
	h2, l2 = bits.Mul64(x[4], x[7])
	h3, l3 = bits.Mul64(x[4], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, _ = bits.Add64(h3, 0, c)
	t9, c = bits.Add64(t9, r0, 0)
	t10, c = bits.Add64(t10, r1, c)
	t11, c = bits.Add64(t11, r2, c)
	t12, c = bits.Add64(t12, r3, c)
	t13, c = bits.Add64(t13, r4, c)
	t14 = c
	// Cross products with x[5].
	h0, l0 = bits.Mul64(x[5], x[6])
	h1, l1 = bits.Mul64(x[5], x[7])
	h2, l2 = bits.Mul64(x[5], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, _ = bits.Add64(h2, 0, c)
	t11, c = bits.Add64(t11, r0, 0)
	t12, c = bits.Add64(t12, r1, c)
	t13, c = bits.Add64(t13, r2, c)
	t14, c = bits.Add64(t14, r3, c)
	t15 = c
	// Cross products with x[6].
	h0, l0 = bits.Mul64(x[6], x[7])
	h1, l1 = bits.Mul64(x[6], x[8])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, _ = bits.Add64(h1, 0, c)
	t13, c = bits.Add64(t13, r0, 0)
	t14, c = bits.Add64(t14, r1, c)
	t15, c = bits.Add64(t15, r2, c)
	t16 = c
	// Cross products with x[7].
	h0, l0 = bits.Mul64(x[7], x[8])
	r0 = l0
	r1 = h0
	t15, c = bits.Add64(t15, r0, 0)
	t16, c = bits.Add64(t16, r1, c)
	t17 = c
	// Double the cross products; t0 is zero.
	t17 = t17<<1 | t16>>63
	t16 = t16<<1 | t15>>63
	t15 = t15<<1 | t14>>63
	t14 = t14<<1 | t13>>63
	t13 = t13<<1 | t12>>63
	t12 = t12<<1 | t11>>63
	t11 = t11<<1 | t10>>63
	t10 = t10<<1 | t9>>63
	t9 = t9<<1 | t8>>63
	t8 = t8<<1 | t7>>63
	t7 = t7<<1 | t6>>63
	t6 = t6<<1 | t5>>63
	t5 = t5<<1 | t4>>63
	t4 = t4<<1 | t3>>63
	t3 = t3<<1 | t2>>63
	t2 = t2<<1 | t1>>63
	t1 <<= 1
	// Add the squares of the limbs.
	h0, l0 = bits.Mul64(x[0], x[0])
	h1, l1 = bits.Mul64(x[1], x[1])
	h2, l2 = bits.Mul64(x[2], x[2])
	h3, l3 = bits.Mul64(x[3], x[3])
	h4, l4 = bits.Mul64(x[4], x[4])
	h5, l5 = bits.Mul64(x[5], x[5])
	h6, l6 = bits.Mul64(x[6], x[6])
	h7, l7 = bits.Mul64(x[7], x[7])
	h8, l8 = bits.Mul64(x[8], x[8])
	t0, c = bits.Add64(t0, l0, 0)
	t1, c = bits.Add64(t1, h0, c)
	t2, c = bits.Add64(t2, l1, c)
	t3, c = bits.Add64(t3, h1, c)
	t4, c = bits.Add64(t4, l2, c)
	t5, c = bits.Add64(t5, h2, c)
	t6, c = bits.Add64(t6, l3, c)
	t7, c = bits.Add64(t7, h3, c)
	t8, c = bits.Add64(t8, l4, c)
	t9, c = bits.Add64(t9, h4, c)
	t10, c = bits.Add64(t10, l5, c)
	t11, c = bits.Add64(t11, h5, c)
	t12, c = bits.Add64(t12, l6, c)
	t13, c = bits.Add64(t13, h6, c)
	t14, c = bits.Add64(t14, l7, c)
	t15, c = bits.Add64(t15, h7, c)
	t16, c = bits.Add64(t16, l8, c)
	t17, c = bits.Add64(t17, h8, c)
	// Reduce: add pTop·M at limb N−1 and keep the high N limbs.
	h0, l0 = bits.Mul64(t0, fpPTop)
	m := t8 + l0 // the top limb of M
	h1, l1 = bits.Mul64(t1, fpPTop)
	h2, l2 = bits.Mul64(t2, fpPTop)
	h3, l3 = bits.Mul64(t3, fpPTop)
	h4, l4 = bits.Mul64(t4, fpPTop)
	h5, l5 = bits.Mul64(t5, fpPTop)
	h6, l6 = bits.Mul64(t6, fpPTop)
	h7, l7 = bits.Mul64(t7, fpPTop)
	h8, l8 = bits.Mul64(m, fpPTop)
	var c2, rTop uint64
	r1, c2 = bits.Add64(l1, h0, 0)
	r2, c2 = bits.Add64(l2, h1, c2)
	r3, c2 = bits.Add64(l3, h2, c2)
	r4, c2 = bits.Add64(l4, h3, c2)
	r5, c2 = bits.Add64(l5, h4, c2)
	r6, c2 = bits.Add64(l6, h5, c2)
	r7, c2 = bits.Add64(l7, h6, c2)
	r8, c2 = bits.Add64(l8, h7, c2)
	rTop, _ = bits.Add64(h8, 0, c2)
	_, c = bits.Add64(t8, l0, 0)
	t9, c = bits.Add64(t9, r1, c)
	t10, c = bits.Add64(t10, r2, c)
	t11, c = bits.Add64(t11, r3, c)
	t12, c = bits.Add64(t12, r4, c)
	t13, c = bits.Add64(t13, r5, c)
	t14, c = bits.Add64(t14, r6, c)
	t15, c = bits.Add64(t15, r7, c)
	t16, c = bits.Add64(t16, r8, c)
	t17, _ = bits.Add64(t17, rTop, c)
	var b uint64
	t9, b = bits.Sub64(t9, 0xffffffffffffffff, 0)
	t10, b = bits.Sub64(t10, 0xffffffffffffffff, b)
	t11, b = bits.Sub64(t11, 0xffffffffffffffff, b)
	t12, b = bits.Sub64(t12, 0xffffffffffffffff, b)
	t13, b = bits.Sub64(t13, 0xffffffffffffffff, b)
	t14, b = bits.Sub64(t14, 0xffffffffffffffff, b)
	t15, b = bits.Sub64(t15, 0xffffffffffffffff, b)
	t16, b = bits.Sub64(t16, 0xffffffffffffffff, b)
	t17, b = bits.Sub64(t17, fpPTop-1, b)
	mask := -b
	z[0], c = bits.Add64(t9, mask, 0)
	z[1], c = bits.Add64(t10, mask, c)
	z[2], c = bits.Add64(t11, mask, c)
	z[3], c = bits.Add64(t12, mask, c)
	z[4], c = bits.Add64(t13, mask, c)
	z[5], c = bits.Add64(t14, mask, c)
	z[6], c = bits.Add64(t15, mask, c)
	z[7], c = bits.Add64(t16, mask, c)
	z[8], c = bits.Add64(t17, (fpPTop-1)&mask, c)
}

// fromMontgomery returns the canonical integer value of x as little-endian
// limbs.
func fromMontgomery(x *fp) [fpLimbs]uint64 {
	var c, h, l uint64
	t := x.l
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[8] = 0
	t[7], c = bits.Add64(t[7], l, 0)
	t[8], _ = bits.Add64(t[8], h, c)
	return t
}
