// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build amd64 && !purego

package p566

import (
	"os"
	"slices"
	"strings"
	"testing"
)

// TestHasBMI2AndADX checks the CPUID test of the assembly against the CPU
// flags that Linux reports, so that a wrong test cannot silently disable
// the assembly.
func TestHasBMI2AndADX(t *testing.T) {
	t.Parallel()

	cpuinfo, err := os.ReadFile("/proc/cpuinfo")
	if err != nil {
		t.Skipf("reading the CPU flags: %v", err)
	}

	for line := range strings.Lines(string(cpuinfo)) {
		name, value, ok := strings.Cut(line, ":")
		if !ok || strings.TrimSpace(name) != "flags" {
			continue
		}

		flags := strings.Fields(value)
		want := slices.Contains(flags, "bmi2") && slices.Contains(flags, "adx")

		if got := hasBMI2AndADX(); got != want {
			t.Fatalf("hasBMI2AndADX() = %v, but /proc/cpuinfo has flags %q", got, flags)
		}

		return
	}

	t.Skip("/proc/cpuinfo has no CPU flags")
}

// TestFpFallback runs mul and square with useAsm cleared, as on a CPU
// without BMI2 and ADX, so that fpMul and fpSquare jump to the Go code.
//
//nolint:paralleltest // The test changes useAsm, which the parallel tests read.
func TestFpFallback(t *testing.T) {
	saved := useAsm
	useAsm = false

	t.Cleanup(func() { useAsm = saved })

	checkMulMatchesGeneric(t, newTestRand(t.Name()), 1000)
}

// TestFpAsm checks the assembly against the generated Go code directly.
func TestFpAsm(t *testing.T) {
	t.Parallel()

	if !hasBMI2AndADX() {
		t.Skip("the CPU lacks BMI2 or ADX")
	}

	rnd := newTestRand(t.Name())

	for range 1000 {
		elemX, elemY := fromBig(t, randBig(rnd)), fromBig(t, randBig(rnd))

		var got, want [fpLimbs]uint64

		fpMulGeneric(&want, &elemX.l, &elemY.l)

		if fpMulAsm(&got, &elemX.l, &elemY.l); got != want {
			t.Fatalf("fpMulAsm(%x, %x) = %x, want %x", elemX.l, elemY.l, got, want)
		}

		fpSquareGeneric(&want, &elemX.l)

		if fpSquareAsm(&got, &elemX.l); got != want {
			t.Fatalf("fpSquareAsm(%x) = %x, want %x", elemX.l, got, want)
		}
	}
}
