// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build !purego

package p566

// The assembly in fp_amd64.s is generated by internal/asmgen. The functions
// with the Asm suffix need the BMI2 and ADX extensions, which Intel CPUs have
// since Broadwell and AMD CPUs since Zen. The functions without a suffix jump
// to them if useAsm is set, and to the Go functions with the Generic suffix
// otherwise. Because the check is in the assembly, the methods that call them
// stay small enough to be inlined.

//nolint:gochecknoglobals // CPUID is slow, so the result is computed once.
var useAsm = hasBMI2AndADX()

func hasBMI2AndADX() bool

//go:noescape
func fpMul(z, x, y *[fpLimbs]uint64)

//go:noescape
func fpSquare(z, x *[fpLimbs]uint64)

//go:noescape
func fpMulAsm(z, x, y *[fpLimbs]uint64)

//go:noescape
func fpSquareAsm(z, x *[fpLimbs]uint64)

//go:noescape
func fp2Mul(z, x, y *fp2)

//go:noescape
func fp2Square(z, x *fp2)

//go:noescape
func fp2MulAsm(z, x, y *fp2)

//go:noescape
func fp2SquareAsm(z, x *fp2)

//go:noescape
func theta4Hadamard(p *theta4)

//go:noescape
func theta4HadamardAsm(p *theta4)

// mul sets z = x·y and returns z.
func (z *fp) mul(x, y *fp) *fp {
	fpMul(&z.l, &x.l, &y.l)

	return z
}

// square sets z = x² and returns z.
func (z *fp) square(x *fp) *fp {
	fpSquare(&z.l, &x.l)

	return z
}

// mul sets z = x·y and returns z.
func (z *fp2) mul(x, y *fp2) *fp2 {
	fp2Mul(z, x, y)

	return z
}

// square sets z = x² and returns z.
func (z *fp2) square(x *fp2) *fp2 {
	fp2Square(z, x)

	return z
}
