// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p566

// The functions in this file sample a deterministic basis of E[2^n] for a
// public curve E. They take variable time, which is fine because their
// inputs are public.

// maxSamplingAttempts bounds the searches for a suitable x-coordinate.
// Heuristically, about half of the candidates succeed, so an honest public
// key reaches the bound with negligible probability; it only stops crafted
// inputs from looping.
const maxSamplingAttempts = 128

// isOnCurve returns 1 if x is the x-coordinate of a point on c defined over
// GF(p²).
func (c *curve) isOnCurve(x *fp2) uint64 {
	var rhs, one fp2

	rhs.add(x, &c.a).mul(&rhs, x).add(&rhs, one.one()).mul(&rhs, x)

	return rhs.isSquare()
}

// fullOrderPointFromA returns x(P) for a point P of order divisible by 2^f,
// assuming A is not a square. The x-coordinate is the first multiple
// x = k·A, for k = 1, 2, ..., that lies on the curve.
func (c *curve) fullOrderPointFromA() (pointX, bool) {
	var res pointX

	res.x = c.a
	res.z.one()

	for range maxSamplingAttempts {
		if c.isOnCurve(&res.x) == 1 {
			return res, true
		}

		res.x.add(&res.x, &c.a)
	}

	return res, false
}

// fullOrderPointFromNQR returns x(P) for a point P of order divisible by 2^f,
// assuming A is a square. It returns (−A : 1 + i·h) for the smallest h ≥ 1
// such that 1 + h² is not a square in GF(p) and the point lies on the curve.
// The candidates for h come from fpNonSquareSteps, which has
// maxSamplingAttempts entries.
func (c *curve) fullOrderPointFromNQR() (pointX, bool) {
	var res pointX

	res.x.neg(&c.a)

	var aSquared, lhs, zSquared fp2

	aSquared.square(&c.a)

	for _, step := range fpNonSquareSteps {
		// −A/(1 + i·h) is on the curve if A²·(z − 1) − z² is not a square,
		// for z = 1 + i·h.
		res.z.one()
		res.z.im.setUint64(uint64(step))
		lhs.zero()
		lhs.im.setUint64(uint64(step))
		lhs.mul(&aSquared, &lhs)
		zSquared.square(&res.z)

		if lhs.sub(&lhs, &zSquared).isSquare() == 0 {
			return res, true
		}
	}

	return res, false
}

// projectiveDifference returns x(P − Q) or x(P + Q), given x(P) and x(Q).
// Which of the two is returned depends on the projective representatives
// and matches the reference implementation.
func (c *curve) projectiveDifference(ptP, ptQ *pointX) pointX {
	// x(P ± Q) are the roots of bxx·x² − 2·bxz·x + bzz.
	var tmp0, tmp1, bxx, bxz, bzz fp2

	tmp0.mul(&ptP.x, &ptQ.x)
	tmp1.mul(&ptP.z, &ptQ.z)
	bxx.sub(&tmp0, &tmp1).square(&bxx)
	bxz.add(&tmp0, &tmp1)
	tmp0.mul(&ptP.x, &ptQ.z)
	tmp1.mul(&ptP.z, &ptQ.x)
	bzz.add(&tmp0, &tmp1)
	bxz.mul(&bxz, &bzz)
	bzz.sub(&tmp0, &tmp1).square(&bzz)
	tmp0.mul(&tmp0, &tmp1).mul(&tmp0, &c.a).double(&tmp0)
	bxz.add(&bxz, &tmp0)

	// Scale by conj(PZ·QZ)², following the reference implementation.
	tmp0.conjugate(&ptP.z)
	tmp1.conjugate(&ptQ.z)
	tmp0.mul(&tmp0, &tmp1).square(&tmp0)
	bxx.mul(&bxx, &tmp0)
	bxz.mul(&bxz, &tmp0)
	bzz.mul(&bzz, &tmp0)

	// Solve the quadratic. Its roots x(P ± Q) lie in GF(p²), so the
	// discriminant is a square.
	tmp0.square(&bxz)
	tmp1.mul(&bxx, &bzz)
	tmp0.sub(&tmp0, &tmp1)
	tmp0.sqrt(&tmp0)

	var res pointX

	res.x.add(&bxz, &tmp0)
	res.z = bzz

	return res
}

// torsionBasis returns a basis of E[2^n] as x-only points, where the curve
// order is (c·2^f)² and shift = f − n. It also returns false if no point
// could be sampled, which happens only for invalid curves. A must not be in
// GF(p).
func (c *curve) torsionBasis(shift int, cofactor uint64) (basisX, bool) {
	// Sample a point P whose order is divisible by 2^f. Whether A is a square
	// decides the method; A is public, so branching on it is fine.
	var (
		basePt pointX
		found  bool
	)

	if c.a.isSquare() == 0 {
		basePt, found = c.fullOrderPointFromA()
	} else {
		basePt, found = c.fullOrderPointFromNQR()
	}

	// The point R with x(R) = −(x(P) + A) is also on the curve, has order
	// divisible by 2^f, and is independent of P, as in the torsion basis
	// algorithm the MIKE paper cites ([AAA+26, Alg. 4.94]). The basis is
	// then x(P), x(Q) = x(P ± R), and x(P − Q) = x(R).
	var diffPt pointX

	diffPt.x.mul(&basePt.z, &c.a).add(&diffPt.x, &basePt.x).neg(&diffPt.x)
	diffPt.z = basePt.z

	basePt = c.xmul(&basePt, cofactor)
	diffPt = c.xmul(&diffPt, cofactor)
	c.xdblN(&basePt, shift)
	c.xdblN(&diffPt, shift)

	otherPt := c.projectiveDifference(&basePt, &diffPt)

	return basisX{p: basePt, q: otherPt, pq: diffPt}, found
}

// liftBasis returns Jacobian points P and Q such that x(P), x(Q), and
// x(P − Q) match the basis.
func (c *curve) liftBasis(basis *basisX) (point, point) {
	var ptP point

	ptP.x = basis.p.affineX()

	var tmp fp2

	ptP.y.square(&ptP.x)
	ptP.y.add(&ptP.y, tmp.mul(&ptP.x, &c.a))
	ptP.y.add(&ptP.y, tmp.one())
	ptP.y.mul(&ptP.y, &ptP.x)
	ptP.y.sqrt(&ptP.y) // x(P) is the x-coordinate of a point over GF(p²), so this succeeds.
	ptP.z.one()

	return ptP, c.recoverQ(&ptP, basis)
}

// recoverQ returns the Jacobian point Q of the basis, given its lift P, with
// the formula of Okeya and Sakurai.
func (c *curve) recoverQ(ptP *point, basis *basisX) point {
	var ptQ point

	ptQ.x, ptQ.z = basis.q.x, basis.q.z
	diffX, diffZ := basis.pq.x, basis.pq.z

	var tmp1, tmp2, tmp3, tmp4 fp2

	tmp1.mul(&ptP.x, &ptQ.z)
	tmp2.add(&ptQ.x, &tmp1)
	tmp3.sub(&ptQ.x, &tmp1).square(&tmp3).mul(&tmp3, &diffX)
	tmp1.double(&c.a).mul(&tmp1, &ptQ.z)
	tmp2.add(&tmp2, &tmp1)
	tmp4.mul(&ptP.x, &ptQ.x).add(&tmp4, &ptQ.z)
	tmp2.mul(&tmp2, &tmp4)
	tmp1.mul(&tmp1, &ptQ.z)
	tmp2.sub(&tmp2, &tmp1).mul(&tmp2, &diffZ)
	ptQ.y.sub(&tmp3, &tmp2)
	tmp1.double(&ptP.y).mul(&tmp1, &ptQ.z).mul(&tmp1, &diffZ)
	ptQ.x.mul(&ptQ.x, &tmp1)
	ptQ.z.mul(&ptQ.z, &tmp1)
	tmp1.square(&ptQ.z)
	ptQ.y.mul(&ptQ.y, &tmp1)
	ptQ.x.mul(&ptQ.x, &ptQ.z)

	return ptQ
}
