// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p474

import "math/bits"

// This file drives the dimension-4 isogeny chain of the shared secret
// computation, from E × E^σ × E × E^σ to the fourfold whose invariants form
// the shared secret.
//
// The kernel is generated by two points of order 2^(e+2) above it. Each
// 2-isogeny step needs the multiples of order 8 of the kernel generators. A
// balanced strategy saves intermediate multiples on a stack, so that the
// chain needs O(e log e) doublings and evaluations instead of O(e²)
// doublings.
//
// Stack entry i holds two kernel generators and a level, levels[i]. A level
// of 1 means the generators are ready for the next step. Each step consumes
// the top entry and lowers the level of the entries below it by one. The
// first step is the three-isogeny gluing, which starts from points on E; the
// remaining e − 3 steps are 2-isogenies between theta structures.

const (
	// generators is the number of kernel generators in a stack entry.
	generators = 2

	// gluingDepth is the number of 2-isogenies in the gluing beyond the one
	// step it counts as.
	gluingDepth = 2

	// curveSaveLevel is the level from which advance saves an intermediate
	// multiple of curve points instead of doubling all the way.
	curveSaveLevel = 64
)

// isogenyChain returns the codomain of the 2^exp-isogeny with the given
// kernel data. The curve point pairs in kernel generate the kernel, and
// gluing holds the kernel data for the gluing steps. aDiv3 must be A/3.
func (c *curve) isogenyChain(aDiv3 *fp2, gluing *kernelPoints, kernel *[generators]pointPair, exp int) theta4Structure {
	steps := exp - gluingDepth
	space := bits.Len(uint(steps)) + 1
	levels := make([]int, space)
	pairs := make([]pointPair, generators*space)
	pairs[0], pairs[1] = kernel[0], kernel[1]
	levels[0] = steps

	top := c.advance(aDiv3, pairs, levels, 0)
	// The gluing consumes the top entry and maps the entries below it to
	// theta points, which become the bottom of the new stack.
	domain, points := gluingIsogeny(c, gluing, pairs[:generators*top])
	points = append(points, make([]theta4, generators*space-len(points))...)
	top = pop(levels, top)

	return thetaChain(domain, points, levels, top, steps-1)
}

// scalarThetaChain runs steps 2-isogeny steps from domain, with the stack of
// theta points in points, and returns the last codomain. thetaChain calls it
// when the vector code path is unavailable; vecThetaChain in
// thetavec_amd64.go mirrors it.
func scalarThetaChain(domain theta4Structure, points []theta4, levels []int, top, steps int) theta4Structure {
	for range steps {
		top = domain.advance(points, levels, top)
		gen1, gen2 := points[generators*top], points[generators*top+1]
		domain = twoIsogeny4(&gen1, &gen2, points[:generators*top])
		top = pop(levels, top)
	}

	return domain
}

// pop removes the top entry of the stack after an isogeny step and returns
// the new top index.
func pop(levels []int, top int) int {
	for i := range top {
		levels[i]--
	}

	return max(top-1, 0)
}

// advance doubles the curve points on the stack until the top entry has
// level 1, and returns the new top index.
func (c *curve) advance(aDiv3 *fp2, pairs []pointPair, levels []int, top int) int {
	for levels[top] != 1 {
		top++
		// Pushing points through the gluing is expensive, so for short
		// remaining lengths double all the way instead of saving more
		// intermediate points.
		prev := levels[top-1]

		doublings := prev - 1
		if prev >= curveSaveLevel {
			doublings = prev >> 1
		}

		for gen := range generators {
			for comp := range pairs[0] {
				src := &pairs[generators*(top-1)+gen][comp]
				pairs[generators*top+gen][comp] = c.doubleNFast(src, aDiv3, doublings)
			}
		}

		levels[top] = prev - doublings
	}

	return top
}

// advance doubles the theta points on the stack until the top entry has
// level 1, and returns the new top index. advanceVec in thetavec_amd64.go
// mirrors it.
func (s *theta4Structure) advance(points []theta4, levels []int, top int) int {
	for levels[top] != 1 {
		top++

		prev := levels[top-1]
		doublings := prev >> 1

		for gen := range generators {
			dst := &points[generators*top+gen]
			*dst = points[generators*(top-1)+gen]
			s.doubleN(dst, doublings)
		}

		levels[top] = prev - doublings
	}

	return top
}
