// Code generated by internal/gen. DO NOT EDIT.

package p474

import "math/bits"

// Field constants for p = 593·2^474 − 1, a 484-bit prime. Elements
// use 8 limbs, and R = 2^(64·8) is the Montgomery constant.
const (
	fpLimbs = 8
	fpSize  = 61 // the length of an encoded element in bytes

	fpPTop = 0x944000000 // the top limb of p + 1; the other limbs are zero
)

var (
	fpP       = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000943ffffff}
	fpR       = [fpLimbs]uint64{0x000000001ba10679, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00000006dc000000}
	fpR2      = [fpLimbs]uint64{0xdb43e357d2d5c027, 0xdde53c01ba10679b, 0x6b0ff917be61909e, 0xc01ba10679bd8488, 0x917be61909edde53, 0x10679bd84886b0ff, 0x61909edde53c01ba, 0x00000001b3f917be}
	fpExpInv  = [fpLimbs]uint64{0xfffffffffffffffd, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x0000000943ffffff} // p − 2
	fpExpSqrt = [fpLimbs]uint64{0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000251000000} // (p + 1)/4
	fpExpLeg  = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x00000004a1ffffff} // (p − 1)/2
)

// add sets z = x + y and returns z.
func (z *fp) add(x, y *fp) *fp {
	var c, b uint64
	t0, c := bits.Add64(x.l[0], y.l[0], 0)
	t1, c := bits.Add64(x.l[1], y.l[1], c)
	t2, c := bits.Add64(x.l[2], y.l[2], c)
	t3, c := bits.Add64(x.l[3], y.l[3], c)
	t4, c := bits.Add64(x.l[4], y.l[4], c)
	t5, c := bits.Add64(x.l[5], y.l[5], c)
	t6, c := bits.Add64(x.l[6], y.l[6], c)
	t7, c := bits.Add64(x.l[7], y.l[7], c)
	u0, b := bits.Sub64(t0, fpP[0], 0)
	u1, b := bits.Sub64(t1, fpP[1], b)
	u2, b := bits.Sub64(t2, fpP[2], b)
	u3, b := bits.Sub64(t3, fpP[3], b)
	u4, b := bits.Sub64(t4, fpP[4], b)
	u5, b := bits.Sub64(t5, fpP[5], b)
	u6, b := bits.Sub64(t6, fpP[6], b)
	u7, b := bits.Sub64(t7, fpP[7], b)
	m := -b
	z.l[0] = u0 ^ (m & (u0 ^ t0))
	z.l[1] = u1 ^ (m & (u1 ^ t1))
	z.l[2] = u2 ^ (m & (u2 ^ t2))
	z.l[3] = u3 ^ (m & (u3 ^ t3))
	z.l[4] = u4 ^ (m & (u4 ^ t4))
	z.l[5] = u5 ^ (m & (u5 ^ t5))
	z.l[6] = u6 ^ (m & (u6 ^ t6))
	z.l[7] = u7 ^ (m & (u7 ^ t7))
	return z
}

// sub sets z = x − y and returns z.
func (z *fp) sub(x, y *fp) *fp {
	var b, c uint64
	t0, b := bits.Sub64(x.l[0], y.l[0], 0)
	t1, b := bits.Sub64(x.l[1], y.l[1], b)
	t2, b := bits.Sub64(x.l[2], y.l[2], b)
	t3, b := bits.Sub64(x.l[3], y.l[3], b)
	t4, b := bits.Sub64(x.l[4], y.l[4], b)
	t5, b := bits.Sub64(x.l[5], y.l[5], b)
	t6, b := bits.Sub64(x.l[6], y.l[6], b)
	t7, b := bits.Sub64(x.l[7], y.l[7], b)
	m := -b
	z.l[0], c = bits.Add64(t0, fpP[0]&m, 0)
	z.l[1], c = bits.Add64(t1, fpP[1]&m, c)
	z.l[2], c = bits.Add64(t2, fpP[2]&m, c)
	z.l[3], c = bits.Add64(t3, fpP[3]&m, c)
	z.l[4], c = bits.Add64(t4, fpP[4]&m, c)
	z.l[5], c = bits.Add64(t5, fpP[5]&m, c)
	z.l[6], c = bits.Add64(t6, fpP[6]&m, c)
	z.l[7], c = bits.Add64(t7, fpP[7]&m, c)
	return z
}

// fpMulGeneric sets z = x·y/R mod p. The inputs must be below p, and z may
// alias them.
func fpMulGeneric(z, x, y *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8 uint64
	var h0, h1, h2, h3, h4, h5, h6, h7 uint64
	var l0, l1, l2, l3, l4, l5, l6, l7 uint64
	var r0, r1, r2, r3, r4, r5, r6, r7, r8 uint64
	// Row 0: t += x·y[0].
	h0, l0 = bits.Mul64(x[0], y[0])
	h1, l1 = bits.Mul64(x[1], y[0])
	h2, l2 = bits.Mul64(x[2], y[0])
	h3, l3 = bits.Mul64(x[3], y[0])
	h4, l4 = bits.Mul64(x[4], y[0])
	h5, l5 = bits.Mul64(x[5], y[0])
	h6, l6 = bits.Mul64(x[6], y[0])
	h7, l7 = bits.Mul64(x[7], y[0])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 1: t += x·y[1].
	h0, l0 = bits.Mul64(x[0], y[1])
	h1, l1 = bits.Mul64(x[1], y[1])
	h2, l2 = bits.Mul64(x[2], y[1])
	h3, l3 = bits.Mul64(x[3], y[1])
	h4, l4 = bits.Mul64(x[4], y[1])
	h5, l5 = bits.Mul64(x[5], y[1])
	h6, l6 = bits.Mul64(x[6], y[1])
	h7, l7 = bits.Mul64(x[7], y[1])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 2: t += x·y[2].
	h0, l0 = bits.Mul64(x[0], y[2])
	h1, l1 = bits.Mul64(x[1], y[2])
	h2, l2 = bits.Mul64(x[2], y[2])
	h3, l3 = bits.Mul64(x[3], y[2])
	h4, l4 = bits.Mul64(x[4], y[2])
	h5, l5 = bits.Mul64(x[5], y[2])
	h6, l6 = bits.Mul64(x[6], y[2])
	h7, l7 = bits.Mul64(x[7], y[2])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 3: t += x·y[3].
	h0, l0 = bits.Mul64(x[0], y[3])
	h1, l1 = bits.Mul64(x[1], y[3])
	h2, l2 = bits.Mul64(x[2], y[3])
	h3, l3 = bits.Mul64(x[3], y[3])
	h4, l4 = bits.Mul64(x[4], y[3])
	h5, l5 = bits.Mul64(x[5], y[3])
	h6, l6 = bits.Mul64(x[6], y[3])
	h7, l7 = bits.Mul64(x[7], y[3])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 4: t += x·y[4].
	h0, l0 = bits.Mul64(x[0], y[4])
	h1, l1 = bits.Mul64(x[1], y[4])
	h2, l2 = bits.Mul64(x[2], y[4])
	h3, l3 = bits.Mul64(x[3], y[4])
	h4, l4 = bits.Mul64(x[4], y[4])
	h5, l5 = bits.Mul64(x[5], y[4])
	h6, l6 = bits.Mul64(x[6], y[4])
	h7, l7 = bits.Mul64(x[7], y[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 5: t += x·y[5].
	h0, l0 = bits.Mul64(x[0], y[5])
	h1, l1 = bits.Mul64(x[1], y[5])
	h2, l2 = bits.Mul64(x[2], y[5])
	h3, l3 = bits.Mul64(x[3], y[5])
	h4, l4 = bits.Mul64(x[4], y[5])
	h5, l5 = bits.Mul64(x[5], y[5])
	h6, l6 = bits.Mul64(x[6], y[5])
	h7, l7 = bits.Mul64(x[7], y[5])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 6: t += x·y[6].
	h0, l0 = bits.Mul64(x[0], y[6])
	h1, l1 = bits.Mul64(x[1], y[6])
	h2, l2 = bits.Mul64(x[2], y[6])
	h3, l3 = bits.Mul64(x[3], y[6])
	h4, l4 = bits.Mul64(x[4], y[6])
	h5, l5 = bits.Mul64(x[5], y[6])
	h6, l6 = bits.Mul64(x[6], y[6])
	h7, l7 = bits.Mul64(x[7], y[6])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	// Row 7: t += x·y[7].
	h0, l0 = bits.Mul64(x[0], y[7])
	h1, l1 = bits.Mul64(x[1], y[7])
	h2, l2 = bits.Mul64(x[2], y[7])
	h3, l3 = bits.Mul64(x[3], y[7])
	h4, l4 = bits.Mul64(x[4], y[7])
	h5, l5 = bits.Mul64(x[5], y[7])
	h6, l6 = bits.Mul64(x[6], y[7])
	h7, l7 = bits.Mul64(x[7], y[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, c = bits.Add64(l7, h6, c)
	r8, _ = bits.Add64(h7, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	t6, c = bits.Add64(t6, r6, c)
	t7, c = bits.Add64(t7, r7, c)
	t8, c = bits.Add64(t8, r8, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = t6
	t6 = t7
	t7 = t8
	t8 = 0
	t6, c = bits.Add64(t6, l0, 0)
	t7, _ = bits.Add64(t7, h0, c)
	var b uint64
	u0, b := bits.Sub64(t0, fpP[0], 0)
	u1, b := bits.Sub64(t1, fpP[1], b)
	u2, b := bits.Sub64(t2, fpP[2], b)
	u3, b := bits.Sub64(t3, fpP[3], b)
	u4, b := bits.Sub64(t4, fpP[4], b)
	u5, b := bits.Sub64(t5, fpP[5], b)
	u6, b := bits.Sub64(t6, fpP[6], b)
	u7, b := bits.Sub64(t7, fpP[7], b)
	m := -b
	z[0] = u0 ^ (m & (u0 ^ t0))
	z[1] = u1 ^ (m & (u1 ^ t1))
	z[2] = u2 ^ (m & (u2 ^ t2))
	z[3] = u3 ^ (m & (u3 ^ t3))
	z[4] = u4 ^ (m & (u4 ^ t4))
	z[5] = u5 ^ (m & (u5 ^ t5))
	z[6] = u6 ^ (m & (u6 ^ t6))
	z[7] = u7 ^ (m & (u7 ^ t7))
}

// fpSquareGeneric sets z = x²/R mod p. The input must be below p, and z may
// alias it.
func fpSquareGeneric(z, x *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15 uint64
	var h0, h1, h2, h3, h4, h5, h6, h7 uint64
	var l0, l1, l2, l3, l4, l5, l6, l7 uint64
	var r0, r1, r2, r3, r4, r5, r6, r7 uint64
	// Cross products with x[0].
	h0, l0 = bits.Mul64(x[0], x[1])
	h1, l1 = bits.Mul64(x[0], x[2])
	h2, l2 = bits.Mul64(x[0], x[3])
	h3, l3 = bits.Mul64(x[0], x[4])
	h4, l4 = bits.Mul64(x[0], x[5])
	h5, l5 = bits.Mul64(x[0], x[6])
	h6, l6 = bits.Mul64(x[0], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, c = bits.Add64(l6, h5, c)
	r7, _ = bits.Add64(h6, 0, c)
	t1, c = bits.Add64(t1, r0, 0)
	t2, c = bits.Add64(t2, r1, c)
	t3, c = bits.Add64(t3, r2, c)
	t4, c = bits.Add64(t4, r3, c)
	t5, c = bits.Add64(t5, r4, c)
	t6, c = bits.Add64(t6, r5, c)
	t7, c = bits.Add64(t7, r6, c)
	t8, c = bits.Add64(t8, r7, c)
	t9 = c
	// Cross products with x[1].
	h0, l0 = bits.Mul64(x[1], x[2])
	h1, l1 = bits.Mul64(x[1], x[3])
	h2, l2 = bits.Mul64(x[1], x[4])
	h3, l3 = bits.Mul64(x[1], x[5])
	h4, l4 = bits.Mul64(x[1], x[6])
	h5, l5 = bits.Mul64(x[1], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, c = bits.Add64(l5, h4, c)
	r6, _ = bits.Add64(h5, 0, c)
	t3, c = bits.Add64(t3, r0, 0)
	t4, c = bits.Add64(t4, r1, c)
	t5, c = bits.Add64(t5, r2, c)
	t6, c = bits.Add64(t6, r3, c)
	t7, c = bits.Add64(t7, r4, c)
	t8, c = bits.Add64(t8, r5, c)
	t9, c = bits.Add64(t9, r6, c)
	t10 = c
	// Cross products with x[2].
	h0, l0 = bits.Mul64(x[2], x[3])
	h1, l1 = bits.Mul64(x[2], x[4])
	h2, l2 = bits.Mul64(x[2], x[5])
	h3, l3 = bits.Mul64(x[2], x[6])
	h4, l4 = bits.Mul64(x[2], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t5, c = bits.Add64(t5, r0, 0)
	t6, c = bits.Add64(t6, r1, c)
	t7, c = bits.Add64(t7, r2, c)
	t8, c = bits.Add64(t8, r3, c)
	t9, c = bits.Add64(t9, r4, c)
	t10, c = bits.Add64(t10, r5, c)
	t11 = c
	// Cross products with x[3].
	h0, l0 = bits.Mul64(x[3], x[4])
	h1, l1 = bits.Mul64(x[3], x[5])
	h2, l2 = bits.Mul64(x[3], x[6])
	h3, l3 = bits.Mul64(x[3], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, _ = bits.Add64(h3, 0, c)
	t7, c = bits.Add64(t7, r0, 0)
	t8, c = bits.Add64(t8, r1, c)
	t9, c = bits.Add64(t9, r2, c)
	t10, c = bits.Add64(t10, r3, c)
	t11, c = bits.Add64(t11, r4, c)
	t12 = c
	// Cross products with x[4].
	h0, l0 = bits.Mul64(x[4], x[5])
	h1, l1 = bits.Mul64(x[4], x[6])
	h2, l2 = bits.Mul64(x[4], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, _ = bits.Add64(h2, 0, c)
	t9, c = bits.Add64(t9, r0, 0)
	t10, c = bits.Add64(t10, r1, c)
	t11, c = bits.Add64(t11, r2, c)
	t12, c = bits.Add64(t12, r3, c)
	t13 = c
	// Cross products with x[5].
	h0, l0 = bits.Mul64(x[5], x[6])
	h1, l1 = bits.Mul64(x[5], x[7])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, _ = bits.Add64(h1, 0, c)
	t11, c = bits.Add64(t11, r0, 0)
	t12, c = bits.Add64(t12, r1, c)
	t13, c = bits.Add64(t13, r2, c)
	t14 = c
	// Cross products with x[6].
	h0, l0 = bits.Mul64(x[6], x[7])
	r0 = l0
	r1 = h0
	t13, c = bits.Add64(t13, r0, 0)
	t14, c = bits.Add64(t14, r1, c)
	t15 = c
	// Double the cross products; t0 is zero.
	t15 = t15<<1 | t14>>63
	t14 = t14<<1 | t13>>63
	t13 = t13<<1 | t12>>63
	t12 = t12<<1 | t11>>63
	t11 = t11<<1 | t10>>63
	t10 = t10<<1 | t9>>63
	t9 = t9<<1 | t8>>63
	t8 = t8<<1 | t7>>63
	t7 = t7<<1 | t6>>63
	t6 = t6<<1 | t5>>63
	t5 = t5<<1 | t4>>63
	t4 = t4<<1 | t3>>63
	t3 = t3<<1 | t2>>63
	t2 = t2<<1 | t1>>63
	t1 <<= 1
	// Add the squares of the limbs.
	h0, l0 = bits.Mul64(x[0], x[0])
	h1, l1 = bits.Mul64(x[1], x[1])
	h2, l2 = bits.Mul64(x[2], x[2])
	h3, l3 = bits.Mul64(x[3], x[3])
	h4, l4 = bits.Mul64(x[4], x[4])
	h5, l5 = bits.Mul64(x[5], x[5])
	h6, l6 = bits.Mul64(x[6], x[6])
	h7, l7 = bits.Mul64(x[7], x[7])
	t0, c = bits.Add64(t0, l0, 0)
	t1, c = bits.Add64(t1, h0, c)
	t2, c = bits.Add64(t2, l1, c)
	t3, c = bits.Add64(t3, h1, c)
	t4, c = bits.Add64(t4, l2, c)
	t5, c = bits.Add64(t5, h2, c)
	t6, c = bits.Add64(t6, l3, c)
	t7, c = bits.Add64(t7, h3, c)
	t8, c = bits.Add64(t8, l4, c)
	t9, c = bits.Add64(t9, h4, c)
	t10, c = bits.Add64(t10, l5, c)
	t11, c = bits.Add64(t11, h5, c)
	t12, c = bits.Add64(t12, l6, c)
	t13, c = bits.Add64(t13, h6, c)
	t14, c = bits.Add64(t14, l7, c)
	t15, c = bits.Add64(t15, h7, c)
	// Reduce: add pTop·M at limb N−1 and keep the high N limbs.
	h0, l0 = bits.Mul64(t0, fpPTop)
	m := t7 + l0 // the top limb of M
	h1, l1 = bits.Mul64(t1, fpPTop)
	h2, l2 = bits.Mul64(t2, fpPTop)
	h3, l3 = bits.Mul64(t3, fpPTop)
	h4, l4 = bits.Mul64(t4, fpPTop)
	h5, l5 = bits.Mul64(t5, fpPTop)
	h6, l6 = bits.Mul64(t6, fpPTop)
	h7, l7 = bits.Mul64(m, fpPTop)
	var c2, rTop uint64
	r1, c2 = bits.Add64(l1, h0, 0)
	r2, c2 = bits.Add64(l2, h1, c2)
	r3, c2 = bits.Add64(l3, h2, c2)
	r4, c2 = bits.Add64(l4, h3, c2)
	r5, c2 = bits.Add64(l5, h4, c2)
	r6, c2 = bits.Add64(l6, h5, c2)
	r7, c2 = bits.Add64(l7, h6, c2)
	rTop, _ = bits.Add64(h7, 0, c2)
	_, c = bits.Add64(t7, l0, 0)
	t8, c = bits.Add64(t8, r1, c)
	t9, c = bits.Add64(t9, r2, c)
	t10, c = bits.Add64(t10, r3, c)
	t11, c = bits.Add64(t11, r4, c)
	t12, c = bits.Add64(t12, r5, c)
	t13, c = bits.Add64(t13, r6, c)
	t14, c = bits.Add64(t14, r7, c)
	t15, _ = bits.Add64(t15, rTop, c)
	var b uint64
	u0, b := bits.Sub64(t8, fpP[0], 0)
	u1, b := bits.Sub64(t9, fpP[1], b)
	u2, b := bits.Sub64(t10, fpP[2], b)
	u3, b := bits.Sub64(t11, fpP[3], b)
	u4, b := bits.Sub64(t12, fpP[4], b)
	u5, b := bits.Sub64(t13, fpP[5], b)
	u6, b := bits.Sub64(t14, fpP[6], b)
	u7, b := bits.Sub64(t15, fpP[7], b)
	msk := -b
	z[0] = u0 ^ (msk & (u0 ^ t8))
	z[1] = u1 ^ (msk & (u1 ^ t9))
	z[2] = u2 ^ (msk & (u2 ^ t10))
	z[3] = u3 ^ (msk & (u3 ^ t11))
	z[4] = u4 ^ (msk & (u4 ^ t12))
	z[5] = u5 ^ (msk & (u5 ^ t13))
	z[6] = u6 ^ (msk & (u6 ^ t14))
	z[7] = u7 ^ (msk & (u7 ^ t15))
}

// fromMontgomery returns the canonical integer value of x as little-endian
// limbs.
func fromMontgomery(x *fp) [fpLimbs]uint64 {
	var c, h, l uint64
	t := x.l
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[7] = 0
	t[6], c = bits.Add64(t[6], l, 0)
	t[7], _ = bits.Add64(t[7], h, c)
	return t
}
