// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

//go:build goexperiment.simd

package p474

import (
	"math/bits"
	"simd/archsimd"
)

// vfp holds four elements of GF(p), one per 64-bit lane of AVX2 vectors.
// Each element is split into vecLimbs limbs of radix 2^vecRadix, and z[i]
// holds limb i of the four elements. The limbs are small enough that
// VPMULUDQ can multiply them, and that a column of a product can be summed
// without carries.
//
// A lane holds the Montgomery form of its element, as fp does, but it is not
// fully reduced. A vfp is normalized when every limb is below 2^vecRadix.
// The arithmetic in fpvec_arith_amd64.go then has these bounds:
//
//   - mul and square take normalized values below 48p, and return
//     normalized values below 2p.
//   - Their Montgomery constant is R_v = 2^(vecRadix·vecLimbs), not R. So
//     the product of the elements x and y comes out as x·y·ρ, where
//     ρ = R/R_v. Callers fold powers of ρ⁻¹ into constants, so that results
//     match the scalar code exactly.
//
// The methods run in constant time. The CPU must support AVX2.
type vfp [vecLimbs]archsimd.Uint64x4

// normBias is a multiple of 2^vecRadix that makes the limbs that normalize
// takes nonnegative.
const normBias = 1 << 62

// set sets the lanes of z to the elements of x.
func (z *vfp) set(x *[4]fp) {
	// words[w] holds 64-bit limb w of the four elements, and a zero limb
	// above them.
	var words [fpLimbs + 1]archsimd.Uint64x4
	for word := range fpLimbs {
		words[word] = archsimd.LoadUint64x4Array(&[4]uint64{x[0].l[word], x[1].l[word], x[2].l[word], x[3].l[word]})
	}

	mask := archsimd.BroadcastUint64x4(vecMask)

	for limb := range uint64(vecLimbs) {
		word, shift := vecLimbPosition(limb)
		if word >= fpLimbs {
			z[limb] = archsimd.Uint64x4{}

			continue
		}

		// A limb that straddles two words takes its high bits from the next
		// one. words has a zero word at the end for the last limb.
		digit := words[word].ShiftRight(vecShiftCount(shift))
		if shift+vecRadix > limbBits {
			digit = digit.Or(words[min(word+1, fpLimbs)].ShiftLeft(vecShiftCount(limbBits - shift)))
		}

		z[limb] = digit.And(mask)
	}
}

// broadcast sets every lane of z to x.
func (z *vfp) broadcast(x *fp) {
	lanes := [4]fp{*x, *x, *x, *x}
	z.set(&lanes)
}

// vecShiftCount returns a vector of shift counts for ShiftLeft and
// ShiftRight. For ShiftAllLeft and ShiftAllRight with a variable count, the
// compiler moves the count with a legacy SSE instruction, which made set
// about 30 times slower on AMD Zen 3.
func vecShiftCount(count uint64) archsimd.Uint64x4 {
	return archsimd.BroadcastUint64x4(count)
}

// vecLimbPosition returns the 64-bit limb in which vector limb i starts, and
// its bit offset there.
func vecLimbPosition(i uint64) (uint64, uint64) {
	bit := vecRadix * i

	return bit / limbBits, bit % limbBits
}

// elements returns the four elements of z, which must be normalized and
// below 2p.
func (z *vfp) elements() [4]fp {
	// The limbs occupy disjoint bits, and the values fit in fpLimbs 64-bit
	// limbs because they are below 2p. The extra word collects the top
	// bits of the last limb, which are zero.
	var words [fpLimbs + 1]archsimd.Uint64x4

	for limb := range uint64(vecLimbs) {
		word, shift := vecLimbPosition(limb)
		if word >= fpLimbs {
			continue
		}

		words[word] = words[word].Or(z[limb].ShiftLeft(vecShiftCount(shift)))

		if shift+vecRadix > limbBits {
			next := min(word+1, fpLimbs)
			words[next] = words[next].Or(z[limb].ShiftRight(vecShiftCount(limbBits - shift)))
		}
	}

	var lanes [fpLimbs][4]uint64
	for word := range lanes {
		words[word].StoreArray(&lanes[word])
	}

	// The rest is scalar code, which the compiler may give SSE instructions.
	// Clearing the upper halves of the vector registers first halves the
	// cost of this function on AMD Zen 3.
	archsimd.ClearAVXUpperBits()

	var out [4]fp

	for word := range lanes {
		for lane := range out {
			out[lane].l[word] = lanes[word][lane]
		}
	}

	for lane := range out {
		out[lane].reduceOnce(&out[lane])
	}

	return out
}

// reduceOnce sets z = elem mod p, for elem < 2p.
func (z *fp) reduceOnce(elem *fp) {
	var (
		diff   fp
		borrow uint64
	)

	for i := range diff.l {
		diff.l[i], borrow = bits.Sub64(elem.l[i], fpP[i], borrow)
	}

	z.selectFrom(elem, &diff, borrow)
}

// normalize propagates the carries of z so that every limb is below
// 2^vecRadix. The limbs of z may be negative, as two's complement int64
// values, but each must lie in (−2^61, 2^61), and the value of each lane in
// [0, R_v).
func (z *vfp) normalize() {
	// Adding normBias leaves the low vecRadix bits of a limb unchanged and
	// makes it nonnegative, so a logical shift gives the signed carry plus
	// normBias/2^vecRadix.
	bias := archsimd.BroadcastUint64x4(normBias)
	unbias := archsimd.BroadcastUint64x4(normBias >> vecRadix)
	mask := archsimd.BroadcastUint64x4(vecMask)

	var carry archsimd.Uint64x4

	for limb := range vecLimbs - 1 {
		biased := z[limb].Add(carry).Add(bias)
		z[limb] = biased.And(mask)
		carry = biased.ShiftAllRight(vecRadix).Sub(unbias)
	}

	z[vecLimbs-1] = z[vecLimbs-1].Add(carry)
}
