// Code generated by internal/gen. DO NOT EDIT.

package p474

// The FastMIKE-III parameter set.
const (
	// The prime is p = primeCofactor·2^primeExponent − 1 = 593·2^474 − 1.
	primeCofactor = 593
	primeExponent = 474

	// isogenyExponent is e: the secret isogeny has degree 2^e.
	isogenyExponent = 340
)

// The starting curve E0: y² = x³ + A·x² + x, and x(P0), x(Q0), and
// x(P0 − Q0) for a basis (P0, Q0) of E0[2^(e+2)] with [2^(e+1)]Q0 = (0, 0),
// as hex encodings of elements of GF(p²).
const (
	startingCurveA = "651718b367b85da78fce3261b932fbb1fb4d2fc70ffd99d6c774719ffd4c5633e44076407ca6c13e33daa2e36098264d76b27f26ed47257be32f5e2e0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXP        = "bfe4e9507c35960654f437c45e33a958f458409610aab7f3595805c5111908d1c04e32b83f44ea3a96276e5a5e580373f2005107d6a20f621a4280400200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXQ        = "fd605be2934f2bdff681fbfa7a55af30b91da08f8f02377dcb590426455ebe0ca730d41c18a294f09cf1cf0d61978d5969dd5934e1d72ca1f89debcd0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXPQ       = "dea2a21988c2e07225bb99df6c44acc4563bf012505677b812d98475ab3be3eeb33f83ea2b73bf95990c1fb4df7748e62d6fd59d5b3d9e8109f0350702804ee84cebc5f1d615f29eb3a112ee26bdf5b9306b5133530d03c6c95c2101229316389bd5e530ac5ec9bef056535c65217dc64a9e8c5e6a96448e3707"
)

// fourIsogenySplits[l] is the number of multiplications by 4 that the chain
// of key generation applies to a point at level l, one that needs l of them
// to generate a 4-isogeny, before saving it. The entries follow an optimal
// strategy for the costs of multiplying by 4 and of evaluating a 4-isogeny,
// which keeps at most fourIsogenyStackSize points.
var fourIsogenySplits = [...]uint16{
	0, 1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 6, 7, 7,
	8, 8, 8, 8, 9, 9, 9, 9, 10, 11, 12, 12, 12, 13, 14, 15,
	15, 15, 15, 15, 16, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21,
	21, 21, 21, 21, 21, 22, 23, 24, 25, 26, 27, 27, 27, 27, 27, 27,
	28, 28, 29, 30, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	33, 34, 35, 36, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 48, 48, 48, 48, 48,
	48, 49, 49, 49, 49, 49, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59,
	60, 61, 62, 63, 64, 65, 65, 65, 66, 67, 68, 69, 70, 70, 70, 70,
	70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
}

const fourIsogenyStackSize = 10

// thetaSplits[l] is the number of doublings that the theta chain of the
// shared secret applies to an entry at level l ≥ 2 before saving it. The
// entries follow an optimal strategy for the costs of doubling, of
// evaluating a 2-isogeny, and of the values for doubling on each codomain,
// which keeps at most thetaStackDepth entries for one entry.
var thetaSplits = [...]uint16{
	0, 0, 1, 1, 1, 2, 3, 3, 4, 3, 4, 4, 5, 6, 6, 7,
	6, 7, 7, 8, 7, 8, 9, 10, 10, 10, 11, 10, 11, 11, 12, 13,
	13, 14, 15, 14, 15, 14, 15, 16, 17, 17, 17, 17, 18, 17, 18, 18,
	19, 18, 19, 20, 21, 22, 23, 23, 23, 23, 24, 25, 26, 25, 26, 25,
	26, 25, 26, 27, 28, 28, 28, 28, 28, 29, 28, 29, 30, 31, 31, 31,
	32, 33, 34, 33, 34, 33, 34, 33, 34, 35, 36, 37, 38, 39, 40, 40,
	40, 40, 40, 40, 40, 41, 42, 43, 44, 43, 44, 43, 44, 43, 44, 43,
	44, 45, 46, 46, 46, 46, 46, 46, 47, 46, 47, 48, 47, 48, 49, 50,
	51, 52, 53, 54, 54, 54, 54, 54, 54, 55, 56, 57, 58, 59, 60, 59,
	60, 59, 60, 59, 60, 59, 60, 59, 60, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 69, 70, 71,
	72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 74, 75, 76, 77,
	77, 77, 77, 77, 77, 77, 78, 77, 78, 78, 79, 80, 81, 82, 81, 82,
	81, 82, 81, 82, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 95, 96, 97,
	98, 99, 100, 101, 102, 103, 104, 103, 104, 103, 104, 103, 104, 103, 104, 103,
	104, 103, 104, 103, 104, 103, 104, 103, 104, 103, 104, 105, 106, 107, 108, 109,
	110, 111, 112, 113, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114, 114,
	114, 114, 114, 114, 115, 116, 117, 118, 119, 120, 119, 120, 119, 120, 119, 120,
	119, 120, 119, 120, 119, 120, 121, 122, 123, 122, 123, 124, 125, 126, 127, 128,
	129, 130, 131, 131, 131, 131, 131, 131, 131, 131, 132, 131, 132, 132, 132, 132,
	132, 132,
}

const thetaStackDepth = 12
