// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p628

import (
	"bytes"
	"errors"
	"math/big"
	"testing"
)

func TestSharedSecret(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())
	privA, privB := randomPrivateKey(rnd), randomPrivateKey(rnd)
	pubA, pubB := PublicKey(privA), PublicKey(privB)

	secretA, err := SharedSecret(privA, pubB)
	if err != nil {
		t.Fatal(err)
	}

	secretB, err := SharedSecret(privB, pubA)
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(secretA, secretB) {
		t.Fatalf("shared secrets differ: %x and %x", secretA, secretB)
	}
}

// encodePublicKey returns the encoding of re + i·im, for integers in [0, p).
func encodePublicKey(re, im *big.Int) []byte {
	enc := func(val *big.Int) []byte { return reverse(val.FillBytes(make([]byte, fpSize))) }

	return append(enc(re), enc(im)...)
}

func TestPublicKeyValidation(t *testing.T) {
	t.Parallel()

	zero, one := big.NewInt(0), big.NewInt(1)
	two := new(big.Int).Add(one, one)
	minusTwo := new(big.Int).Sub(prime(), two)

	for _, test := range []struct {
		name string
		key  []byte
		want error
	}{
		{"empty", nil, ErrInvalidPublicKey},
		{"short", make([]byte, fp2Size-1), ErrInvalidPublicKey},
		{"long", make([]byte, fp2Size+1), ErrInvalidPublicKey},
		{"non-canonical real part", encodePublicKey(prime(), one), ErrInvalidPublicKey},
		{"non-canonical imaginary part", encodePublicKey(one, prime()), ErrInvalidPublicKey},
		{"zero", encodePublicKey(zero, zero), ErrUnsupportedPublicKey},
		{"in GF(p)", encodePublicKey(one, zero), ErrUnsupportedPublicKey},
		{"A = 2", encodePublicKey(two, zero), ErrUnsupportedPublicKey},
		{"A = −2", encodePublicKey(minusTwo, zero), ErrUnsupportedPublicKey},
	} {
		err := CheckPublicKey(test.key)
		if !errors.Is(err, test.want) {
			t.Errorf("%s: got %v, want %v", test.name, err, test.want)
		}
	}
}

func TestSharedSecretRejectsInvalidCurves(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())
	priv := randomPrivateKey(rnd)
	pub := PublicKey(randomPrivateKey(rnd))

	var coefA fp2

	if !coefA.setBytes(pub) {
		t.Fatal("invalid public key")
	}

	// −A defines an isomorphic curve, but not the normalized one.
	var negated fp2

	negated.neg(&coefA)

	_, err := SharedSecret(priv, negated.bytes())
	if !errors.Is(err, ErrNotNormalized) {
		t.Errorf("non-normalized curve: got %v, want %v", err, ErrNotNormalized)
	}

	// Most curves are ordinary. Try the next few candidates after A, each
	// of which is rejected either while sampling the basis or by the order
	// check.
	var cand, one fp2

	one.one()

	cand = coefA
	for range 5 {
		cand.add(&cand, &one)

		_, err := SharedSecret(priv, cand.bytes())
		if !errors.Is(err, ErrNotSupersingular) {
			t.Errorf("curve %x: got %v, want %v", cand.bytes(), err, ErrNotSupersingular)
		}
	}
}

func BenchmarkPublicKey(b *testing.B) {
	priv := randomPrivateKey(newTestRand(b.Name()))
	for b.Loop() {
		PublicKey(priv)
	}
}

func BenchmarkSharedSecret(b *testing.B) {
	rnd := newTestRand(b.Name())
	priv := randomPrivateKey(rnd)
	pub := PublicKey(randomPrivateKey(rnd))

	for b.Loop() {
		_, err := SharedSecret(priv, pub)
		if err != nil {
			b.Fatal(err)
		}
	}
}
