// Code generated by internal/gen from internal/p308. DO NOT EDIT.

// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p628

import "testing"

func TestTheta4Hadamard(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	// Applying the Hadamard transform twice multiplies by 16.
	var input theta4
	for idx := range input {
		input[idx] = fromBig(t, randBig(rnd))
	}

	twice := input
	twice.hadamard()
	twice.hadamard()

	var sixteen fp

	sixteen.one().mul4(&sixteen).mul4(&sixteen)

	for idx := range input {
		var want fp
		if want.mul(&input[idx], &sixteen).equal(&twice[idx]) != 1 {
			t.Fatal("H(H(P)) ≠ 16·P")
		}
	}
}

func TestTheta4Compressed(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())

	// On points with the symmetry of MIKE null points, the compressed
	// transforms agree with the full ones.
	var compressed theta4c
	for idx := range compressed {
		compressed[idx] = fromBig(t, randBig(rnd))
	}

	full := compressed.expand()
	full.hadamard()
	compressed.hadamard()

	if compressed.expand() != full {
		t.Fatal("compressed Hadamard ≠ full Hadamard")
	}

	full.square()
	compressed.square()

	if compressed.expand() != full {
		t.Fatal("compressed square ≠ full square")
	}

	if compress(&full) != compressed {
		t.Fatal("compress ∘ expand is not the identity")
	}
}

func TestTheta2Hadamard(t *testing.T) {
	t.Parallel()

	rnd := newTestRand(t.Name())
	randFp := func() fp { return fromBig(t, randBig(rnd)) }

	// In dimension 2, applying the Hadamard transform twice multiplies by 4.
	input := theta2{randFp(), randFp(), randFp(), randFp()}
	twice := input
	twice.hadamard()
	twice.hadamard()

	var four fp

	four.one().mul4(&four)

	for _, pair := range [][2]*fp{{&input.x, &twice.x}, {&input.y, &twice.y}, {&input.z, &twice.z}, {&input.t, &twice.t}} {
		var want fp
		if want.mul(pair[0], &four).equal(pair[1]) != 1 {
			t.Fatal("dimension 2: H(H(P)) ≠ 4·P")
		}
	}
}
