// Code generated by internal/gen. DO NOT EDIT.

package p308

import "math/bits"

// Field constants for p = 633·2^308 − 1, a 318-bit prime. Elements
// use 5 limbs, and R = 2^(64·5) is the Montgomery constant.
const (
	fpLimbs = 5
	fpSize  = 40 // the length of an encoded element in bytes

	fpPTop = 0x2790000000000000 // the top limb of p + 1; the other limbs are zero
)

var (
	fpP       = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x278fffffffffffff}
	fpR       = [fpLimbs]uint64{0x0000000000000006, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x12a0000000000000}
	fpR2      = [fpLimbs]uint64{0xa1c4f4458f91ff5a, 0xdc019e2129a7d5f0, 0xb0541ebc761774e0, 0xd1163e47fcc3bdac, 0x1fe4a69f57c28713}
	fpExpInv  = [fpLimbs]uint64{0xfffffffffffffffd, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x278fffffffffffff} // p − 2
	fpExpSqrt = [fpLimbs]uint64{0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x09e4000000000000} // (p + 1)/4
	fpExpLeg  = [fpLimbs]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0x13c7ffffffffffff} // (p − 1)/2
)

// add sets z = x + y and returns z.
func (z *fp) add(x, y *fp) *fp {
	var c, b uint64
	t0, c := bits.Add64(x.l[0], y.l[0], 0)
	t1, c := bits.Add64(x.l[1], y.l[1], c)
	t2, c := bits.Add64(x.l[2], y.l[2], c)
	t3, c := bits.Add64(x.l[3], y.l[3], c)
	t4, c := bits.Add64(x.l[4], y.l[4], c)
	u0, b := bits.Sub64(t0, fpP[0], 0)
	u1, b := bits.Sub64(t1, fpP[1], b)
	u2, b := bits.Sub64(t2, fpP[2], b)
	u3, b := bits.Sub64(t3, fpP[3], b)
	u4, b := bits.Sub64(t4, fpP[4], b)
	m := -b
	z.l[0] = u0 ^ (m & (u0 ^ t0))
	z.l[1] = u1 ^ (m & (u1 ^ t1))
	z.l[2] = u2 ^ (m & (u2 ^ t2))
	z.l[3] = u3 ^ (m & (u3 ^ t3))
	z.l[4] = u4 ^ (m & (u4 ^ t4))
	return z
}

// sub sets z = x − y and returns z.
func (z *fp) sub(x, y *fp) *fp {
	var b, c uint64
	t0, b := bits.Sub64(x.l[0], y.l[0], 0)
	t1, b := bits.Sub64(x.l[1], y.l[1], b)
	t2, b := bits.Sub64(x.l[2], y.l[2], b)
	t3, b := bits.Sub64(x.l[3], y.l[3], b)
	t4, b := bits.Sub64(x.l[4], y.l[4], b)
	m := -b
	z.l[0], c = bits.Add64(t0, fpP[0]&m, 0)
	z.l[1], c = bits.Add64(t1, fpP[1]&m, c)
	z.l[2], c = bits.Add64(t2, fpP[2]&m, c)
	z.l[3], c = bits.Add64(t3, fpP[3]&m, c)
	z.l[4], c = bits.Add64(t4, fpP[4]&m, c)
	return z
}

// fpMulGeneric sets z = x·y/R mod p. The inputs must be below p, and z may
// alias them.
func fpMulGeneric(z, x, y *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5 uint64
	var h0, h1, h2, h3, h4 uint64
	var l0, l1, l2, l3, l4 uint64
	var r0, r1, r2, r3, r4, r5 uint64
	// Row 0: t += x·y[0].
	h0, l0 = bits.Mul64(x[0], y[0])
	h1, l1 = bits.Mul64(x[1], y[0])
	h2, l2 = bits.Mul64(x[2], y[0])
	h3, l3 = bits.Mul64(x[3], y[0])
	h4, l4 = bits.Mul64(x[4], y[0])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = 0
	t3, c = bits.Add64(t3, l0, 0)
	t4, _ = bits.Add64(t4, h0, c)
	// Row 1: t += x·y[1].
	h0, l0 = bits.Mul64(x[0], y[1])
	h1, l1 = bits.Mul64(x[1], y[1])
	h2, l2 = bits.Mul64(x[2], y[1])
	h3, l3 = bits.Mul64(x[3], y[1])
	h4, l4 = bits.Mul64(x[4], y[1])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = 0
	t3, c = bits.Add64(t3, l0, 0)
	t4, _ = bits.Add64(t4, h0, c)
	// Row 2: t += x·y[2].
	h0, l0 = bits.Mul64(x[0], y[2])
	h1, l1 = bits.Mul64(x[1], y[2])
	h2, l2 = bits.Mul64(x[2], y[2])
	h3, l3 = bits.Mul64(x[3], y[2])
	h4, l4 = bits.Mul64(x[4], y[2])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = 0
	t3, c = bits.Add64(t3, l0, 0)
	t4, _ = bits.Add64(t4, h0, c)
	// Row 3: t += x·y[3].
	h0, l0 = bits.Mul64(x[0], y[3])
	h1, l1 = bits.Mul64(x[1], y[3])
	h2, l2 = bits.Mul64(x[2], y[3])
	h3, l3 = bits.Mul64(x[3], y[3])
	h4, l4 = bits.Mul64(x[4], y[3])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = 0
	t3, c = bits.Add64(t3, l0, 0)
	t4, _ = bits.Add64(t4, h0, c)
	// Row 4: t += x·y[4].
	h0, l0 = bits.Mul64(x[0], y[4])
	h1, l1 = bits.Mul64(x[1], y[4])
	h2, l2 = bits.Mul64(x[2], y[4])
	h3, l3 = bits.Mul64(x[3], y[4])
	h4, l4 = bits.Mul64(x[4], y[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, c = bits.Add64(l4, h3, c)
	r5, _ = bits.Add64(h4, 0, c)
	t0, c = bits.Add64(t0, r0, 0)
	t1, c = bits.Add64(t1, r1, c)
	t2, c = bits.Add64(t2, r2, c)
	t3, c = bits.Add64(t3, r3, c)
	t4, c = bits.Add64(t4, r4, c)
	t5, c = bits.Add64(t5, r5, c)
	// Reduce: t = (t + t0·p) / 2^64.
	h0, l0 = bits.Mul64(t0, fpPTop)
	t0 = t1
	t1 = t2
	t2 = t3
	t3 = t4
	t4 = t5
	t5 = 0
	t3, c = bits.Add64(t3, l0, 0)
	t4, _ = bits.Add64(t4, h0, c)
	var b uint64
	u0, b := bits.Sub64(t0, fpP[0], 0)
	u1, b := bits.Sub64(t1, fpP[1], b)
	u2, b := bits.Sub64(t2, fpP[2], b)
	u3, b := bits.Sub64(t3, fpP[3], b)
	u4, b := bits.Sub64(t4, fpP[4], b)
	m := -b
	z[0] = u0 ^ (m & (u0 ^ t0))
	z[1] = u1 ^ (m & (u1 ^ t1))
	z[2] = u2 ^ (m & (u2 ^ t2))
	z[3] = u3 ^ (m & (u3 ^ t3))
	z[4] = u4 ^ (m & (u4 ^ t4))
}

// fpSquareGeneric sets z = x²/R mod p. The input must be below p, and z may
// alias it.
func fpSquareGeneric(z, x *[fpLimbs]uint64) {
	var c uint64
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9 uint64
	var h0, h1, h2, h3, h4 uint64
	var l0, l1, l2, l3, l4 uint64
	var r0, r1, r2, r3, r4 uint64
	// Cross products with x[0].
	h0, l0 = bits.Mul64(x[0], x[1])
	h1, l1 = bits.Mul64(x[0], x[2])
	h2, l2 = bits.Mul64(x[0], x[3])
	h3, l3 = bits.Mul64(x[0], x[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, c = bits.Add64(l3, h2, c)
	r4, _ = bits.Add64(h3, 0, c)
	t1, c = bits.Add64(t1, r0, 0)
	t2, c = bits.Add64(t2, r1, c)
	t3, c = bits.Add64(t3, r2, c)
	t4, c = bits.Add64(t4, r3, c)
	t5, c = bits.Add64(t5, r4, c)
	t6 = c
	// Cross products with x[1].
	h0, l0 = bits.Mul64(x[1], x[2])
	h1, l1 = bits.Mul64(x[1], x[3])
	h2, l2 = bits.Mul64(x[1], x[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, c = bits.Add64(l2, h1, c)
	r3, _ = bits.Add64(h2, 0, c)
	t3, c = bits.Add64(t3, r0, 0)
	t4, c = bits.Add64(t4, r1, c)
	t5, c = bits.Add64(t5, r2, c)
	t6, c = bits.Add64(t6, r3, c)
	t7 = c
	// Cross products with x[2].
	h0, l0 = bits.Mul64(x[2], x[3])
	h1, l1 = bits.Mul64(x[2], x[4])
	r0 = l0
	r1, c = bits.Add64(l1, h0, 0)
	r2, _ = bits.Add64(h1, 0, c)
	t5, c = bits.Add64(t5, r0, 0)
	t6, c = bits.Add64(t6, r1, c)
	t7, c = bits.Add64(t7, r2, c)
	t8 = c
	// Cross products with x[3].
	h0, l0 = bits.Mul64(x[3], x[4])
	r0 = l0
	r1 = h0
	t7, c = bits.Add64(t7, r0, 0)
	t8, c = bits.Add64(t8, r1, c)
	t9 = c
	// Double the cross products; t0 is zero.
	t9 = t9<<1 | t8>>63
	t8 = t8<<1 | t7>>63
	t7 = t7<<1 | t6>>63
	t6 = t6<<1 | t5>>63
	t5 = t5<<1 | t4>>63
	t4 = t4<<1 | t3>>63
	t3 = t3<<1 | t2>>63
	t2 = t2<<1 | t1>>63
	t1 <<= 1
	// Add the squares of the limbs.
	h0, l0 = bits.Mul64(x[0], x[0])
	h1, l1 = bits.Mul64(x[1], x[1])
	h2, l2 = bits.Mul64(x[2], x[2])
	h3, l3 = bits.Mul64(x[3], x[3])
	h4, l4 = bits.Mul64(x[4], x[4])
	t0, c = bits.Add64(t0, l0, 0)
	t1, c = bits.Add64(t1, h0, c)
	t2, c = bits.Add64(t2, l1, c)
	t3, c = bits.Add64(t3, h1, c)
	t4, c = bits.Add64(t4, l2, c)
	t5, c = bits.Add64(t5, h2, c)
	t6, c = bits.Add64(t6, l3, c)
	t7, c = bits.Add64(t7, h3, c)
	t8, c = bits.Add64(t8, l4, c)
	t9, c = bits.Add64(t9, h4, c)
	// Reduce: add pTop·M at limb N−1 and keep the high N limbs.
	h0, l0 = bits.Mul64(t0, fpPTop)
	m := t4 + l0 // the top limb of M
	h1, l1 = bits.Mul64(t1, fpPTop)
	h2, l2 = bits.Mul64(t2, fpPTop)
	h3, l3 = bits.Mul64(t3, fpPTop)
	h4, l4 = bits.Mul64(m, fpPTop)
	var c2, rTop uint64
	r1, c2 = bits.Add64(l1, h0, 0)
	r2, c2 = bits.Add64(l2, h1, c2)
	r3, c2 = bits.Add64(l3, h2, c2)
	r4, c2 = bits.Add64(l4, h3, c2)
	rTop, _ = bits.Add64(h4, 0, c2)
	_, c = bits.Add64(t4, l0, 0)
	t5, c = bits.Add64(t5, r1, c)
	t6, c = bits.Add64(t6, r2, c)
	t7, c = bits.Add64(t7, r3, c)
	t8, c = bits.Add64(t8, r4, c)
	t9, _ = bits.Add64(t9, rTop, c)
	var b uint64
	u0, b := bits.Sub64(t5, fpP[0], 0)
	u1, b := bits.Sub64(t6, fpP[1], b)
	u2, b := bits.Sub64(t7, fpP[2], b)
	u3, b := bits.Sub64(t8, fpP[3], b)
	u4, b := bits.Sub64(t9, fpP[4], b)
	msk := -b
	z[0] = u0 ^ (msk & (u0 ^ t5))
	z[1] = u1 ^ (msk & (u1 ^ t6))
	z[2] = u2 ^ (msk & (u2 ^ t7))
	z[3] = u3 ^ (msk & (u3 ^ t8))
	z[4] = u4 ^ (msk & (u4 ^ t9))
}

// fromMontgomery returns the canonical integer value of x as little-endian
// limbs.
func fromMontgomery(x *fp) [fpLimbs]uint64 {
	var c, h, l uint64
	t := x.l
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[4] = 0
	t[3], c = bits.Add64(t[3], l, 0)
	t[4], _ = bits.Add64(t[4], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[4] = 0
	t[3], c = bits.Add64(t[3], l, 0)
	t[4], _ = bits.Add64(t[4], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[4] = 0
	t[3], c = bits.Add64(t[3], l, 0)
	t[4], _ = bits.Add64(t[4], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[4] = 0
	t[3], c = bits.Add64(t[3], l, 0)
	t[4], _ = bits.Add64(t[4], h, c)
	h, l = bits.Mul64(t[0], fpPTop)
	copy(t[:], t[1:])
	t[4] = 0
	t[3], c = bits.Add64(t[3], l, 0)
	t[4], _ = bits.Add64(t[4], h, c)
	return t
}
