// Copyright 2026 Dwi Siswanto ("dwisiswant0"). All rights reserved.
// Use of this source code is governed by the Apache License, Version 2.0,
// that can be found in the LICENSE file.

package p308

import (
	"math/bits"
	"slices"
)

// This file computes the secret 2^e-isogeny of key generation as a chain of
// 4-isogenies between Montgomery curves, and normalizes the codomain into
// the public key.

// fourIsogeny holds the constants for evaluating the 4-isogeny with kernel
// generated by a point K of order 4, where [2]K ≠ (0 : 1).
type fourIsogeny struct {
	c0, c1, c2 fp2
}

// fourIsogenyDegreeLog is log₂ of the degree of a fourIsogeny.
const fourIsogenyDegreeLog = 2

// newFourIsogeny returns the 4-isogeny with kernel ⟨kernel⟩ and its
// codomain, given as (A + 2)/4 = (a24 : c24).
func newFourIsogeny(kernel *pointX) (fourIsogeny, fp2, fp2) {
	var (
		phi      fourIsogeny
		a24, c24 fp2
	)

	phi.c1.sub(&kernel.x, &kernel.z)
	phi.c2.add(&kernel.x, &kernel.z)
	phi.c0.square(&kernel.z).double(&phi.c0)
	c24.square(&phi.c0)
	phi.c0.double(&phi.c0)
	a24.square(&kernel.x).double(&a24).square(&a24)

	return phi, a24, c24
}

// eval sets dst to its image under the isogeny.
func (phi *fourIsogeny) eval(dst *pointX) {
	var tmp0, tmp1 fp2

	tmp0.add(&dst.x, &dst.z)
	tmp1.sub(&dst.x, &dst.z)
	dst.x.mul(&tmp0, &phi.c1)
	dst.z.mul(&tmp1, &phi.c2)
	tmp0.mul(&tmp0, &tmp1).mul(&tmp0, &phi.c0)
	tmp1.add(&dst.x, &dst.z).square(&tmp1)
	dst.z.sub(&dst.x, &dst.z).square(&dst.z)
	dst.x.add(&tmp0, &tmp1).mul(&dst.x, &tmp1)
	tmp0.sub(&dst.z, &tmp0)
	dst.z.mul(&dst.z, &tmp0)
}

// twoIsogenyChain returns the normalized codomain of the 2^exp-isogeny whose
// kernel is ⟨[4]K⟩. The point K must have order 2^(exp+2) and exp must be
// even.
//
// The chain uses 4-isogenies and a balanced strategy, which keeps O(log exp)
// intermediate multiples of K. The point of order 4 that K maps to on the
// codomain is used for normalization.
func (c *curve) twoIsogenyChain(kernel *pointX, exp int) curve {
	a24 := c.a24

	var c24 fp2

	c24.one()

	// points[i] has order 2^orders[i].
	space := bits.Len(uint(exp))
	points := make([]pointX, space)
	orders := make([]int, space)
	points[0] = *kernel
	orders[0] = exp + fourIsogenyDegreeLog

	top := 0
	for range exp / fourIsogenyDegreeLog {
		// Double towards a point of order 4, saving intermediate multiples.
		// Each push doubles by about half of the remaining exponent, rounded
		// to an even number because each step consumes a factor of 4.
		for orders[top] != fourIsogenyDegreeLog {
			top++
			prev := orders[top-1]
			steps := fourIsogenyDegreeLog*(prev>>fourIsogenyDegreeLog) + (prev & 1)

			points[top] = points[top-1]
			for range steps {
				xdblProj(&points[top], &a24, &c24)
			}

			orders[top] = prev - steps
		}

		var phi fourIsogeny

		phi, a24, c24 = newFourIsogeny(&points[top])
		for i := range top {
			phi.eval(&points[i])
			orders[i] = max(orders[i]-fourIsogenyDegreeLog, 0)
		}

		top = max(top-1, 0)
	}

	return normalizeCurve(&points[0])
}

// normalizeCurve returns the canonical curve for the isomorphism class of
// the curve that contains the point kernel of order 4.
//
// The Montgomery coefficient is determined by a point of order 4 up to six
// choices. Together with their Frobenius conjugates, these are all the
// coefficients for curves isomorphic to E or to its conjugate. The result is
// the coefficient whose encoding is the largest little-endian integer. This
// makes the public key independent of the secret path that produced it.
func normalizeCurve(kernel *pointX) curve {
	num, den := normalizationCandidates(kernel)

	batchInvert(den[:])

	var (
		best    fp2
		bestEnc []byte
	)

	for pair := range num {
		var cands [4]fp2

		cands[0].mul(&num[pair], &den[pair])
		cands[1].neg(&cands[0])
		cands[2].conjugate(&cands[0])
		cands[3].conjugate(&cands[1])

		for _, cand := range cands {
			if bestEnc == nil {
				best, bestEnc = cand, cand.bytes()

				continue
			}

			best.selectFrom(&cand, &best, lessLE(bestEnc, cand.bytes()))
			bestEnc = best.bytes()
		}
	}

	return newCurve(&best)
}

// normalizationCandidates returns the numerators and denominators of the
// three Montgomery coefficients A = −2(a⁴ + b⁴)/(a⁴ − b⁴) determined by the
// point kernel of order 4, up to sign and conjugation.
func normalizationCandidates(kernel *pointX) ([3]fp2, [3]fp2) {
	// Three theta-like coordinate pairs derived from the point (a + b : a − b).
	var (
		lhs, rhs [3]fp2
		tmp      fp2
	)

	lhs[0], rhs[0] = kernel.x, kernel.z
	lhs[1].add(&lhs[0], &rhs[0])
	rhs[1].sub(&lhs[0], &rhs[0])
	lhs[2].add(tmp.mulI(&lhs[1]), &rhs[1])
	rhs[2].add(tmp.mulI(&rhs[1]), &lhs[1])

	var num, den [3]fp2

	for idx := range num {
		var lhs4, rhs4 fp2

		lhs4.squareN(&lhs[idx], fourIsogenyDegreeLog)
		rhs4.squareN(&rhs[idx], fourIsogenyDegreeLog)
		num[idx].add(&lhs4, &rhs4).double(&num[idx]).neg(&num[idx])
		den[idx].sub(&lhs4, &rhs4)
	}

	return num, den
}

// mulI sets z = i·x.
func (z *fp2) mulI(x *fp2) *fp2 {
	re := x.re
	z.re.neg(&x.im)
	z.im = re

	return z
}

// lessLE returns 1 if lhs < rhs as little-endian integers, and 0 otherwise.
// The slices must have the same length. It runs in constant time.
func lessLE(lhs, rhs []byte) uint64 {
	var less, equal uint64 = 0, 1

	for i, v := range slices.Backward(lhs) {
		diff := uint64(v) - uint64(rhs[i])
		less |= equal & (diff >> (limbBits - 1))
		equal &= 1 ^ (diff|-diff)>>(limbBits-1)
	}

	return less
}
