// Code generated by internal/gen. DO NOT EDIT.

package p308

// The FastMIKE-I parameter set.
const (
	// The prime is p = primeCofactor·2^primeExponent − 1 = 633·2^308 − 1.
	primeCofactor = 633
	primeExponent = 308

	// isogenyExponent is e: the secret isogeny has degree 2^e.
	isogenyExponent = 228
)

// The starting curve E0: y² = x³ + A·x² + x, and x(P0), x(Q0), and
// x(P0 − Q0) for a basis (P0, Q0) of E0[2^(e+2)] with [2^(e+1)]Q0 = (0, 0),
// as hex encodings of elements of GF(p²).
const (
	startingCurveA = "def6e76e68069827513779218a11830e5915ea48ae21816ab17e6d720e41de60a5f64591ea3daa1000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXP        = "821354db1ea1337ae966ce69fccfc8a5d377c8869584a1fe0b3f3a3caf2f28b72806b3905941ba2400000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXQ        = "e84711304605676be01e36d5fccedfa59b2446f3a00fb30fd3c17c779c4feeb21300c9635f95491f00000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXPQ       = "b5adb2853253cdf2e442829f7c4fd4a5374e073d1b4a2a876f80dbd9a53f0b351e033e7a5ceb0122f36b7f781a1a13e08abe97f8159b6f2f247ce055e4a1ce2e59950af377bcf6baa3670a9bd2d59f11"
)

// fourIsogenySplits[l] is the number of multiplications by 4 that the chain
// of key generation applies to a point at level l, one that needs l of them
// to generate a 4-isogeny, before saving it. The entries follow an optimal
// strategy for the costs of multiplying by 4 and of evaluating a 4-isogeny,
// which keeps at most fourIsogenyStackSize points.
var fourIsogenySplits = [...]uint16{
	0, 1, 1, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 6, 7, 7,
	8, 8, 8, 8, 9, 9, 9, 9, 10, 11, 12, 12, 12, 13, 14, 15,
	15, 15, 15, 15, 16, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21,
	21, 21, 21, 21, 21, 22, 23, 24, 25, 26, 27, 27, 27, 27, 27, 27,
	28, 28, 29, 30, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	33, 34, 35, 36, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 48, 48, 48, 48, 48,
	48, 49, 49,
}

const fourIsogenyStackSize = 9

// thetaSplits[l] is the number of doublings that the theta chain of the
// shared secret applies to an entry at level l ≥ 2 before saving it. The
// entries follow an optimal strategy for the costs of doubling, of
// evaluating a 2-isogeny, and of the values for doubling on each codomain,
// which keeps at most thetaStackDepth entries for one entry.
var thetaSplits = [...]uint16{
	0, 0, 1, 1, 1, 2, 3, 3, 4, 3, 4, 4, 5, 6, 6, 7,
	6, 7, 7, 8, 7, 8, 9, 10, 10, 10, 11, 10, 11, 11, 12, 13,
	13, 14, 15, 14, 15, 14, 15, 16, 17, 17, 17, 17, 18, 17, 18, 18,
	19, 18, 19, 20, 21, 22, 23, 23, 23, 23, 24, 25, 26, 25, 26, 25,
	26, 25, 26, 27, 28, 28, 28, 28, 28, 29, 28, 29, 30, 31, 31, 31,
	32, 33, 34, 33, 34, 33, 34, 33, 34, 35, 36, 37, 38, 39, 40, 40,
	40, 40, 40, 40, 40, 41, 42, 43, 44, 43, 44, 43, 44, 43, 44, 43,
	44, 45, 46, 46, 46, 46, 46, 46, 47, 46, 47, 48, 47, 48, 49, 50,
	51, 52, 53, 54, 54, 54, 54, 54, 54, 55, 56, 57, 58, 59, 60, 59,
	60, 59, 60, 59, 60, 59, 60, 59, 60, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 69, 70, 71,
	72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 72, 73, 74, 75, 76, 77,
	77, 77, 77, 77, 77, 77, 78, 77, 78, 78, 79, 80, 81, 82, 81, 82,
	81, 82, 81, 82, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94,
}

const thetaStackDepth = 11
