// Code generated by internal/gen. DO NOT EDIT.

package p308

// The FastMIKE-I parameter set.
const (
	// The prime is p = primeCofactor·2^primeExponent − 1 = 633·2^308 − 1.
	primeCofactor = 633
	primeExponent = 308

	// isogenyExponent is e: the secret isogeny has degree 2^e.
	isogenyExponent = 228
)

// The starting curve E0: y² = x³ + A·x² + x, and x(P0), x(Q0), and
// x(P0 − Q0) for a basis (P0, Q0) of E0[2^(e+2)] with [2^(e+1)]Q0 = (0, 0),
// as hex encodings of elements of GF(p²).
const (
	startingCurveA = "def6e76e68069827513779218a11830e5915ea48ae21816ab17e6d720e41de60a5f64591ea3daa1000000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXP        = "821354db1ea1337ae966ce69fccfc8a5d377c8869584a1fe0b3f3a3caf2f28b72806b3905941ba2400000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXQ        = "e84711304605676be01e36d5fccedfa59b2446f3a00fb30fd3c17c779c4feeb21300c9635f95491f00000000000000000000000000000000000000000000000000000000000000000000000000000000"
	basisXPQ       = "b5adb2853253cdf2e442829f7c4fd4a5374e073d1b4a2a876f80dbd9a53f0b351e033e7a5ceb0122f36b7f781a1a13e08abe97f8159b6f2f247ce055e4a1ce2e59950af377bcf6baa3670a9bd2d59f11"
)
